### ISSUE TITLE
Make the IdentityUser class implement an IIdentityUser interface

### ISSUE THREAD

**Issue by BenjaminCharlton** [aspnet/Identity#1181] opened 2017-04-27 10:17 UTC
Would it be possible to make the IdentityUser class implement an IIdentityUser interface, and for the other ASP .NET Identity classes to expose and reference instances of the IIdentityUser interface instead of the IdentityUser class?

The way it is now, my ApplicationUser class lives in my Persistence namespace because it inherits IdentityUser<int>, which resides in Entity Framework. I need to reference the ApplicationUser class in controllers such as AccountsController and ManageController, which means that now my controllers are tightly coupled to Entity Framework too. I would prefer to make my controllers dependent on my Core library, and be persistence ignorant.

I love Entity Framework and ASP .NET Core Identity and want to use both, but I also want to be loosely coupled to them so that I can, if I want, remove Entity Framework but still use ASP .NET Core Identity.

How about....

Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUser<TKey>

...implements...

Microsoft.AspNetCore.Identity.IIdentityUser<TKey>
where TKey : IEquatable<TKey>

...so that my ApplicationUser class can continue to inherit from Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUser<int>....

....but my controllers can instead reference any implentation of Microsoft.AspNetCore.Identity.IIdentityUser<int>

...then they can reference only MyProject.Core and not have to reference MyProject.Persistence.

Please could anybody advise if this is a good idea. If not, why not, and what's the alternative way?

Many thanks for your consideration

Benjamin

**Comment by HaoK** [comment] 2017-04-27 18:38
This is the issue we are using to track some refactoring we will do.  We aren't going to be adding an interface, as we like the ability to work with any kind of POCO.  

That said, we will probably be moving IdentityUser to some kind of base common Provider package that the EF package will derive from, so you won't be forced to pull in EF just to have access to IdentityUser

Closing as dupe of : https://github.com/aspnet/Identity/issues/883

**Closed by HaoK** 2017-04-27 18:38 UTC

**Comment by BenjaminCharlton** [comment] 2017-04-30 12:25
Thanks for the explanation, Haok.

I read about #883 and other related issues with great interest. Is there a way I can receive a notification when this is addressed so I can try out the new version and see if it solves my problem? Advice would be appreciated.
