### ISSUE TITLE
Downgrade from EF7 to EF6

### ISSUE THREAD

**Issue by sgadoury** [aspnet/Identity#725] opened 2016-01-28 15:47 UTC
Hi,

I created the issue #4419 in EntityFramework I juste closed because my problem is not with EF, but with Asp.Net identity.  Since EF7 does not support Oracle, I need to downgrade to EF6.  My problem is with Asp.Net identity.  Do you know how I can downgrade?  Do you have an example of Asp.Net identity with EF6?  It is because I tried to changed EF version and all seems to be link.  Is it possible that Identity functionnality is completely different between version 2 and 3?  I'm using Vs.Net 2015 and Identity code is written by default when I created the application.

Thank you for your help

**Comment by SharePointRadi** [comment] 2016-01-30 08:56
See this: https://github.com/OneBitSoftware/Microsoft.AspNet.Identity.EntityFramework6 

It would be great if MS officially consider this EF provider, however there's lots of drawbacks due to the differences between EF6 and EF7.

**Comment by rustd** [comment] 2016-02-01 23:16
Duplicate of https://github.com/aspnet/Identity/issues/416

**Closed by rustd** 2016-02-01 23:16 UTC

**Comment by sgadoury** [comment] 2016-02-02 01:47
Thank you for your help
