### ISSUE TITLE
Database entities are tied to Entity Framework

### ISSUE THREAD

**Issue by gravity00** [aspnet/Identity#879] opened 2016-06-24 18:59 UTC
At the present moment, database entities are tied to the Entity Framework package.
This brings some problems:

1. **Can't abstract implementation details even using interfaces** - I'm always obliged to add a reference to `Microsoft.AspNetCore.Identity.EntityFrameworkCore` which will bring all of this dependencies (Entity Framework) to the services layer just to use the database POCOs;
2. **Rework when implementing for other ORMs** - lets say I want to create an implementation for NHibernate, Entity Framework 6 or Dapper, I'll have to create my own database entities and be sure they match the exposed by `Microsoft.AspNetCore.Identity.EntityFrameworkCore` to keep compatibility where I could just implement the stores and add a dependency to the entities package;

My suggestion is the following:

Create a new package (example: `Microsoft.AspNetCore.Identity.Entities`) containing all the POCOs that would be a dependency from `Microsoft.AspNetCore.Identity.EntityFrameworkCore` and other store providers could just add the same dependency and focus only in the store implementation. Service layers would just add a dependency to `Microsoft.AspNetCore.Identity.EntityFrameworkCore` and `Microsoft.AspNetCore.Identity.Entities`.

**Comment by HaoK** [comment] 2016-06-24 19:19
The idea is the stores own the entity types.  You can always just copy the classes from the Entity Framework package for reuse in your implementation.  They are simple enough that we did not feel it was necessary to provide a base class implementation.  We can consider doing this in the future if there is enough demand.

**Comment by gravity00** [comment] 2016-06-25 18:26
@HaoK I see the point in that. The thing is, the core project offers a range of interfaces but, even if I want to only use them, I'll need to bring Entity Framework along and there's no simple way to avoid this.

Imagine I'm developing an application that will use ASP.NET Identity and the client wants to add more properties to the entities (lets imagine some metadata properties like `CreatedOn`, `CreatedBy`, `UpdatedOn`, and so on). If I want to use the Entity Framework implementation and the included `IdentityContext`, I'll have to extend the provided POCOs but now my repositories, which purpose is to hide data access implementation details from the business, are returning entities that are tied to a given implementation (which in this case uses Entity Framework). I could create my own replicas, but now I can't use the provided stores and `IdentityContext` because they don't extend from your entities.

- _Should this entities be provided in the core project?_ I also don't think so, because the data model is not relevant to the security logic.
- _Should this entities be provided in as a separate dependency?_ I really believe so, since it would only tie your entities to a know data model but now tying extenders to a given implementation detail (usage of Entity Framework) and would be still be treated as simple POCOs.

**Comment by blowdart** [comment] 2016-08-17 21:19
Dupe of #883

**Closed by blowdart** 2016-08-17 21:19 UTC
Labels: discussion
