### ISSUE TITLE
VNext Web API bearer token authentication

### ISSUE THREAD

**Issue by anavgale** [aspnet/Identity#543] opened 2015-08-13 12:10 UTC
I am sorry if this a repeat.

BUT there is not clear guidance on how to issue bearer token in Web API and use that to secure WEB APIs using Claims are Roles. This was possible in Web Api 2.1/2.2

Can any one share a link which explains the way this is going to work in future. Docs.asp.net does not talk about this yet.

Thanks & Regards,

**Comment by leak** [comment] 2015-08-20 10:25
I'm also interested in this topic. Especially in context with a pure Angular application without using MVC based controllers/pages at all.

All examples i found so far are somewhat outdated and also crazy over-engineered and complicated.

**Comment by stephenstroud** [comment] 2015-08-21 14:33
See here https://github.com/aspnet/Identity/issues/495

**Comment by HaoK** [comment] 2015-09-09 21:32
Yep dupe of 495

**Closed by HaoK** 2015-09-09 21:32 UTC
