### ISSUE TITLE
Identity AddToRole and IsInRole errors : String was not recognized as a valid Boolean

### ISSUE THREAD

**Issue by Cor4xX** [aspnet/Identity#1012] opened 2016-10-31 09:58 UTC
```
        public async Task UpdateRoles(List<string> roles)
        {
            User user = await GetCurrentUser();

            if(roles == null)
            {
                return;
            }

            foreach (var role in roles)
            {
                bool test = await userManager.IsInRoleAsync(user, role);
                if (!test)
                {
                    var roleResult = await userManager.AddToRoleAsync(user, role);
                }
            }
        }
```

Hi, i got a problem when i try to add my user in certain role with Identity Core.
I first want to check if the user is already in Role with IsInRoleAsync method : role = "admin" and i have already "admin" role created in DB.

But the result is an exception : 

```
An unhandled exception occurred while processing the request.
FormatException: String was not recognized as a valid Boolean.
```

The AddToRoleAsync method has the same problem. Register and Login method works great, AddRole in RoleManager works great too. I dont understand the problem.

Could you help me ? Thx !

**Comment by Cor4xX** [comment] 2016-11-04 08:08
I'm still blocked with this issue. Could someone help me please ? Thanks a lot

**Comment by HaoK** [comment] 2016-11-04 08:18
What's your startup look like?  What's the full callstack of the exception?

**Comment by Cor4xX** [comment] 2016-11-04 08:18
https://s22.postimg.org/p0xx8bhkx/image.png

Here's a screen for my tables User, Role and User_Role. Its MySQL database.

**Comment by Cor4xX** [comment] 2016-11-04 08:22
Hey Haok thanks for the answer.

Startup.cs in ConfigureServices method
```
        private void InitIdentityService(IServiceCollection services)
        {
            services.AddIdentity<User, Role>(options => {
                options.Password.RequireDigit = false;
                options.Password.RequireLowercase = true;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = false;
                options.Password.RequiredLength = FrontConstants.PasswordLength;

                // Lockout settings
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(30);
                options.Lockout.MaxFailedAccessAttempts = 10;

                // Cookie settings
                options.Cookies.ApplicationCookie.ExpireTimeSpan = TimeSpan.FromDays(30);
                options.Cookies.ApplicationCookie.LoginPath = "/Account/Login";
                options.Cookies.ApplicationCookie.LogoutPath = "/Account/Logout";

                // User settings
                options.User.RequireUniqueEmail = true;
            })
                    .AddEntityFrameworkStores<Context, int>()
                    .AddDefaultTokenProviders();
            services.AddScoped<IUserClaimsPrincipalFactory<User>, UserClaimsFactory>();
        }
```

Then i get my service in a static SimpleInjector class to avoid to pass UserManager, SigninManager etc in each controller : 
Startup.cs in Configure method
```
            container.RegisterSingleton(provider.GetRequiredService<UserManager<User>>);
            container.RegisterSingleton(provider.GetRequiredService<RoleManager<Role>>);
            container.RegisterSingleton(provider.GetRequiredService<SignInManager<User>>);
```

**Comment by HaoK** [comment] 2016-11-04 08:26
The callstack for where the format exception should be able to point to the problem, what's trying to convert to a boolean?

**Comment by Cor4xX** [comment] 2016-11-04 08:27
```
System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at System.String.System.IConvertible.ToBoolean(IFormatProvider provider)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.<GetResult>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

```

**Comment by Cor4xX** [comment] 2016-11-04 08:28
It's inside Identity, i cant see what's the problem

**Comment by Cor4xX** [comment] 2016-11-04 08:34
Here's how i define my table in DbContext

```
           builder.Entity<User>(i => {
                i.ToTable("users");
                i.HasKey(x => x.Id);
            });
            builder.Entity<Role>(i => {
                i.ToTable("roles");
                i.HasKey(x => x.Id);
            });
            builder.Entity<IdentityUserRole<int>>(i => {
                i.ToTable("user_roles");
                i.HasKey(x => new { x.RoleId, x.UserId });
            });
            builder.Entity<IdentityUserLogin<int>>(i => {
                i.ToTable("user_logins");
                i.HasKey(x => new { x.ProviderKey, x.LoginProvider });
            });
            builder.Entity<IdentityRoleClaim<int>>(i => {
                i.ToTable("role_claims");
                i.HasKey(x => x.Id);
            });
            builder.Entity<IdentityUserClaim<int>>(i => {
                i.ToTable("user_claims");
                i.HasKey(x => x.Id);
            });
            builder.Entity<IdentityUserToken<int>>(i => {
                i.ToTable("user_tokens");
            });
```

**Comment by HaoK** [comment] 2016-11-04 21:07
Can you try to see if context.Roles.First() throws as well?

We think the issue is with the following query which appears in both of those methods `await Roles.SingleOrDefaultAsync(r => r.NormalizedName == normalizedRoleName, cancellationToken);`

**Comment by Cor4xX** [comment] 2016-11-04 21:21
Hey ! Thanks again for the answer. I cant try now but i will do it tomorrow !

**Comment by Cor4xX** [comment] 2016-11-05 13:07
Hi Haok,

context.Roles.First() works great, i get my Admin role who is the only one Role define in DB.
How can i test SingleOrDefaultAsync ?

**Comment by Cor4xX** [comment] 2016-11-07 11:04
What's the next step ? any idea ? I'm totaly lost with this issue, i can't debug at all since i can't access to the library.

**Comment by HaoK** [comment] 2016-11-07 20:19
Can you try the async methods instead?

**Comment by Cor4xX** [comment] 2016-11-07 20:24
Hmmm i dont see any SingleOrDefaultAsync method with intellisense.

**Comment by divega** [comment] 2016-11-07 21:19
> Hmmm i dont see any SingleOrDefaultAsync method with intellisense.

Add `using Microsoft.EntityFrameworkCore;` at the top of the file.

**Comment by Cor4xX** [comment] 2016-11-07 22:17
var test = await this.context.Roles.SingleOrDefaultAsync();

Works great too...

**Comment by divega** [comment] 2016-11-07 23:10
What about this?

``` C#
var name = "some name you hat in the database".Normalize().ToUpperInvariant();
var test = await this.context.Roles.SingleOrDefaultAsync(r => r.NormalizedName == name);
```

**Comment by Cor4xX** [comment] 2016-11-08 09:17
This code works too.

**Comment by Cor4xX** [comment] 2016-11-08 09:17
I got my role normalized and then i got it from DB.

**Comment by Cor4xX** [comment] 2016-11-08 09:22
```
public class Role : IdentityRole<int>
{
}

public class User : IdentityUser<int>
{
}
```

I use this kind of Users and Roles.

In DB context i declare relation and table like this : 

```
            builder.Entity<User>(i => {
                i.ToTable("users");
                i.HasKey(x => x.Id);
            });
            builder.Entity<Role>(i => {
                i.ToTable("roles");
                i.HasKey(x => x.Id);
            });
            builder.Entity<IdentityUserRole<int>>(i => {
                i.ToTable("user_roles");
                i.HasKey(x => new { x.RoleId, x.UserId });
            });
```

Maybe it could help us in our investigation.

**Comment by Cor4xX** [comment] 2016-11-08 09:31
```
        public async Task TestRole(User user)
        {
            var name = "test".Normalize().ToUpperInvariant();
            var role = await this.context.Roles.SingleOrDefaultAsync(r => r.NormalizedName == name);
            this.context.UserRoles.Add(new IdentityUserRole<int>()
            {
                RoleId = role.Id,
                UserId = user.Id
            });

            this.context.SaveChanges();
        }
```
This code works great too : i got my user_roles added in DB.

**Comment by divega** [comment] 2016-11-08 15:17
@Cor4xX thanks for trying these things. I don't have any more guesses. At this point I think a repro project could help. 

Also, re-reading the whole thread in search for clues, I noticed this paragraph:

> Then i set my services in a static SimpleInjector class to avoid to pass UserManager, SigninManager etc in each controller : 
Startup.cs in Configure method
```
            container.RegisterSingleton(provider.GetRequiredService<UserManager<User>>);
            container.RegisterSingleton(provider.GetRequiredService<RoleManager<Role>>);
            container.RegisterSingleton(provider.GetRequiredService<SignInManager<User>>);
```

Assuming I understand correctly, you are effectively changing the lifetime of the manager objects to be per-application singletons. These manager objects have been designed to work as scoped objects for each request. If you start sharing them across multiple requests, I would expect you to get all sorts of errors and possibly data corruption, since they are not thread safe. I am not sure this is enough to explain the particular issues you are seeing though.

**Comment by Cor4xX** [comment] 2016-11-08 16:00
Hi @divega 
First, thanks for your time and responses. I will try to investigate with my collegue next week and analyze your response.

At the moment i can use Role System directly via my context and own repository/unitofwork. It works. 
I will keep you in touch. Thx !

**Comment by Cor4xX** [comment] 2016-11-10 10:44
I'm trying to clean up my solution, but i'm totaly lost with this DI. Is there a way to encapsulate SignInManger, RoleManager and UserManager ? I have IMapper service, and some other services, am i obliged to add all of this services in my controllers' constructor ?

I would like to encapsulate my services into 3 class : IServiceContainer (with unitofwork, cache service, etc), IWebService (automapper, appsettings) and IAccountServiceContainer (all identity manager).

This way i can only pass 3 class/services with DI to my controllers and use it throw my differents projects (Services, DAL, etc)

Could you give me some tips with that ?

**Comment by Cor4xX** [comment] 2016-11-10 13:29
I will illustrate what im trying to do and actually it seems to work. (i still have my problem with Role anyway)

```
            services.AddSingleton<IWebContainer>(sp =>
            {
                var appSettings = sp.GetService(typeof(AppSettings)) as AppSettings;
                var mapper = sp.GetService(typeof(IMapper)) as IMapper;
                return new WebContainer(mapper, appSettings);
            });

            services.AddScoped<IServiceContainer>(sp =>
            {
                var dbContext = sp.GetService(typeof(context)) as context;
                var unitOfWork = new UnitOfWork(dbContext);
                var memoryCache = sp.GetService(typeof(IMemoryCache)) as IMemoryCache;
                return new ServiceContainer(unitOfWork, memoryCache);
            });

            services.AddScoped<IAccountServiceContainer>(sp =>
            {
                var userManager = sp.GetService(typeof(UserManager<User>)) as UserManager<User>;
                var roleManager = sp.GetService(typeof(RoleManager<Role>)) as RoleManager<Role>;
                var siginManager = sp.GetService(typeof(SignInManager<User>)) as SignInManager<User>;
                return new AccountServiceContainer(siginManager, roleManager, userManager);
            });
```

And i have a _CoreController 

```
    public class _CoreController : Controller
    {
        protected IWebContainer WebContainer { get; set; }
        protected IServiceContainer ServiceContainer { get; set; }
        protected IAccountServiceContainer AccountServiceContainer { get; set; }

        public _CoreController(IWebContainer webContainer)
        {
            this.WebContainer = webContainer;
        }

        public _CoreController(IWebContainer webContainer, IServiceContainer serviceContainer)
        {
            this.WebContainer = webContainer;
            this.ServiceContainer = serviceContainer;
        }

        public _CoreController(IWebContainer webContainer, IServiceContainer serviceContainer, IAccountServiceContainer accountServiceContainer)
        {
            this.WebContainer = webContainer;
            this.ServiceContainer = serviceContainer;
            this.AccountServiceContainer = accountServiceContainer;
        }
}
```
That allows me to use the right constructor and the right services depending on which Controller i'm.
I have remove SimpleInjector and now im using Asp Core DI only.

What do you thing about that ? Anyway IsInRoleAsync via UserManager still not working. My AccountServiceContainer is Scoped and not singleton like you said.

**Comment by Cor4xX** [comment] 2016-11-21 11:32
Hey !
I'm coming back with more informations ! We are  finally deciding to use SqlServer because we faced some other problems with MySQL.

And.... everything works !!!! I can use IsInRole method from Identity etc... So the problem was MySQL or MySQL Driver or a combination of Identity and MySql. 

I hope it will help you to investigate.

**Comment by divega** [comment] 2016-11-24 02:44
@Cor4xX if you can still provide a repro project that shows the issue with MySQL we can forward it to the MySQL team.

For the DI question, I am not sure I understand what you are trying to achieve but you can register your own composite service types that depend on services provided by ASP.NET. You should still be careful not to affect the lifetimes of services when you do that. As I mentioned before, such services as UserManager, RoleManager or SignInManager or the DbContext need to be scoped. If you create them as singletons you will end up executing non-thread-safe code from multiple threads.

**Comment by Cor4xX** [comment] 2016-11-28 09:28
@divega Thanks but i will not have time to isolate this problem from my project and i have overwrite so much code (i could check in my SVN). When i got some moment i will share you the project. For the moment i think all the needed code and sql are in this topic.

Thanks for the advice for DI question. Actually it looks like to be well considered since my containers' lifetime are grouped by children requirement. 

(sorry for my bullshit english by the way xD)

**Comment by divega** [comment] 2016-11-28 22:18
I did a bit more investigation and it seems that the exception 

```
An unhandled exception occurred while processing the request.
FormatException: String was not recognized as a valid Boolean.
```

is coming specifically from a convert we add to the compiled expression that converts the `DbDataReader` into a value buffer, in particular around the `TypedRelationalValueBufferFactoryFactory.CreateGetValueExpression()` method:

https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Relational/Storage/TypedRelationalValueBufferFactoryFactory.cs#L167

I don't know what would make EF Core be in a state in which it expects a `bool` but asks the `DbDataReader` for a `string`, unless there is something special about these types in the MySQL provider?

Adding @anpete from EF Core and @gmartinezsan from MySQL to see if they have any insights.

**Comment by ChristianHaase** [comment] 2017-01-31 13:48
Any updates on this issue? I'm receiving this error when trying to add a role to a user.

     await _userManager.AddToRole(user, "Member")

**Comment by gmartinezsan** [comment] 2017-01-31 15:51
@ChristianHaase Which version are you using of MySql.Data ?

**Comment by ChristianHaase** [comment] 2017-01-31 19:13
I'm not actually using MySql.Data. I'm using SapientGuardian.EntityFrameworkCore.MySql

**Comment by gmartinezsan** [comment] 2017-01-31 20:29
@ChristianHaase ok.. I thought you were using our provider for MySQL. (MySQL.Data,EntityFrameworkCore).
I do not know about SapientGuardian,

**Comment by ChristianHaase** [comment] 2017-01-31 20:40
No of course not. My bad! :)

**Comment by divega** [comment] 2017-01-31 20:49
My bad too. I assumed it was the official MySQL provider. @ChristianHaase based on the information I have seen so far, I recommend you create an issue at https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql/issues.

**Comment by gmartinezsan** [comment] 2017-01-31 20:57
@divega 
No problem at all.. I would be happy to help. But in this case I'm afraid I cannot.
@ChristianHaase 
Is thery any chance you would like to give it a try to the official MySQL Provider? 
Or have you already?

**Comment by ChristianHaase** [comment] 2017-01-31 21:01
Thank you @divega, but I'll just give it a go with the official provider.

@gmartinezsan I just tried it, and now I'm getting the following error on `UserManager.CreateAsync(user, password)`

> Connection must be valid and open to commit transaction

**Comment by gmartinezsan** [comment] 2017-01-31 21:06
@ChristianHaase is there any chance you can share your project?

**Comment by ChristianHaase** [comment] 2017-01-31 21:16
Sure. Let me create a github repo. Had plans to do so anyways. I'll link to you once done.

**Comment by ChristianHaase** [comment] 2017-01-31 21:32
Here you go https://github.com/ChristianHaase/OurGhostsOfWar

**Comment by gmartinezsan** [comment] 2017-01-31 22:08
@ChristianHaase taking a look now.

**Comment by gmartinezsan** [comment] 2017-02-01 00:14
@ChristianHaase I see you are already using 6.10.0 which is the latest we have. I think this is an already fixed issue. I will double check and let you know what the results are.

**Comment by ChristianHaase** [comment] 2017-02-03 21:49
Hello @gmartinezsan Any updates? :)

**Comment by gmartinezsan** [comment] 2017-02-03 22:03
@ChristianHaase I tried it and the issue is not related to the Identity provider or EF Core.. the issue is that we do not have a complete support for Async methods which is the one used in the Identity provider. I created a bug so you can follow up the fix. I will work on this next week and share the fix. 
I'm very sorry for the inconveniente.

**Comment by ChristianHaase** [comment] 2017-02-03 22:38
@gmartinezsan That sounds perfect. Thank you for your help. 👍

**Comment by ChristianHaase** [comment] 2017-02-04 00:27
@gmartinezsan Quick question. Why do you only have asynchronous operations, and not both? Why not give the developer the option to choose themselves? Might be a stupid question.

**Comment by gmartinezsan** [comment] 2017-02-16 14:31
@ChristianHaase hi, not a stupid question at all, the requirement for the async method comes from the implementation of the Identity provider. So we either need to find a way to override that, which I see a bit difficult, or we add some async methods on our side so the Identity provider works normally.  
Hope this explains it better.

**Comment by HaoK** [comment] 2017-06-12 17:01
Closing as this is a mysql issue tracked via https://bugs.mysql.com/bug.php?id=84814

**Closed by HaoK** 2017-06-12 17:01 UTC
Labels: External
