### ISSUE TITLE
How do apps work which share database between apps

### ISSUE THREAD

**Issue by rustd** [aspnet/Identity#197] opened 2014-09-04 01:08 UTC
We should figure out how do apps written with 2.0 work when the membership database was shared between different apps.
- App 1&2 was build using MVC5/ Identity 2.0
- App 1 is updated to use MVC 6/ Identity 3.0
- App 2 is still using MVC5/ Identity 2.0
The users of App1&2 should still be able to login. Levi is doing some work to make sure that the Cookies would be compatible.
Do we need to backport anything to 2.0 to make this work?

**Comment by HaoK** [comment] 2015-05-05 00:02
Dupe of https://github.com/aspnet/Identity/issues/457

**Closed by HaoK** 2015-05-05 00:02 UTC
Labels: Features
