### ISSUE TITLE
Microsoft.AspNetCore.Identity Customize

### ISSUE THREAD

**Issue by pMonfared** [aspnet/Identity#924] opened 2016-08-02 19:22 UTC
I want to customize Identity and override everything

Please See This :
https://github.com/pMonfared/Asp.netCoreMultiLayer
```
and run project you will get this error :
An exception of type 'System.ArgumentException' occurred in System.Private.CoreLib.ni.dll but was not handled in user code

Additional information: GenericArguments[0], 'SampleFive.DomainLayer.Models.ApplicationUser', on 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`4[TUser,TRole,TContext,TKey]' violates the constraint of type 'TUser'.
```

from this location in startup file :

```
 services.AddIdentity<ApplicationUser, ApplicationRole>()
                .AddUserStore<ApplicationUserStore>()
                .AddUserManager<ApplicationUserManager>()
                .AddRoleStore<ApplicationRoleManager>()
                .AddRoleManager<ApplicationRoleManager>()
                .AddEntityFrameworkStores<ApplicationDbContext, string>()
                .AddDefaultTokenProviders();
```

**Comment by ttaber** [comment] 2016-08-02 21:27
See #855 , PR #893 & #918

**Comment by HaoK** [comment] 2016-08-02 21:37
You also cannot use `.AddEntityFrameworkStores<ApplicationDbContext, string>()` when you customize everything, your calls to `AddUserStore/RoleStore` make that call unnecessary as well. so you should be able to remove that line.

**Comment by pMonfared** [comment] 2016-08-03 02:56
i use for Dependency Injection in my project with `"StructureMap.Microsoft.DependencyInjection": "1.0.1"`
but when i config 
```
private IServiceProvider IocConfig(IServiceCollection services)
        {
            var container = new Container();
            container.Configure(config =>
            {
                config.For<IConfigurationRoot>().Singleton().Use(() => Configuration);
                
                config.For<IUserStore<ApplicationUser>>().Use<UserStore<ApplicationUser,ApplicationRole,ApplicationDbContext,string,ApplicationUserClaim,ApplicationUserRole,ApplicationUserLogin,ApplicationUserToken>>();

                config.Scan(_ =>
                {
                    _.AssemblyContainingType<ISettingService>();
                    _.WithDefaultConventions();
                });
                config.For<IRoleStore<ApplicationRole>>().Use<ApplicationRoleStore>();
                config.For<IApplicationRoleStore>().Use<ApplicationRoleStore>();
                config.For<IApplicationUserStore>().Use<ApplicationUserStore>();
                config.For<IApplicationUserManager>().Use<ApplicationUserManager>();
                config.For<IApplicationRoleManager>().Use<ApplicationRoleManager>();
                config.For<IEmailSender>().Use<AuthMessageSender>();
                config.For<ISmsSender>().Use<AuthMessageSender>();

            });

            container.Populate(services);

            return container.GetInstance<IServiceProvider>();
        }
```
i have got error in this line 
```
config.For<IUserStore<ApplicationUser>>().Use<UserStore<ApplicationUser,ApplicationRole,ApplicationDbContext,string,ApplicationUserClaim,ApplicationUserRole,ApplicationUserLogin,ApplicationUserToken>>();
```
error description:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0311	The type 'SampleFive.DomainLayer.Models.ApplicationRole' cannot be used as type parameter 'TRole' in the generic type or method 'UserStore<TUser, TRole, TContext, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken>'. There is no implicit reference conversion from 'SampleFive.DomainLayer.Models.ApplicationRole' to 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRole<string, SampleFive.DomainLayer.Models.ApplicationUserRole, Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRoleClaim<string>>'.	SampleFive.Web..NETCoreApp,Version=v1.0	E:\Programming Projects\GitReps\CustomizeAspdotnetCore\SampleFive.Web\Startup.cs	157	Active

```
this is my ApplicationUser Class:
```
public class ApplicationUser : IdentityUser<string, ApplicationUserClaim, ApplicationUserRole, ApplicationUserLogin>
    {
        public ApplicationUser()
        {
            this.UserUsedPasswords = new List<ApplicationUserUsedPassword>();
        }
        public ICollection<ApplicationUserUsedPassword> UserUsedPasswords { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }
    }

    public class ApplicationRole : IdentityRole<string, ApplicationUserRole, ApplicationRoleClaim>
    
    {
        public string Description { get; set; }
        public ApplicationRole()
        {
        }

        public ApplicationRole(string name)
            : this()
        {
            Name = name;
        }

        public ApplicationRole(string name, string description)
            : this(name)
        {
            this.Description = description;
        }

    }

    public class ApplicationUserLogin : IdentityUserLogin<string>
    {

    }
    public class ApplicationUserRole : IdentityUserRole<string>
    {

    }
    public class ApplicationRoleClaim : IdentityRoleClaim<string>
    {

    }
    public class ApplicationUserClaim : IdentityUserClaim<string>
    {

    }

    public class ApplicationUserToken : IdentityUserToken<string>
    {

    }

    public class ApplicationUserUsedPassword
    {
        public ApplicationUserUsedPassword()
        {
            CreatedDate = DateTimeOffset.UtcNow;
        }
        [Key]
        public int Id { get; set; }

        [Key, Column(Order = 0)]
        public string HashPassword { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        [Key, Column(Order = 1)]
        public string UserId { get; set; }
        public virtual ApplicationUser AppUser { get; set; }
    }
```

**Comment by furlanrapha** [comment] 2016-08-03 13:56
Having same issues too, created this PR #923 to fix this.

**Comment by HaoK** [comment] 2016-08-08 20:26
Dupe of https://github.com/aspnet/Identity/issues/855

**Closed by HaoK** 2016-08-08 20:26 UTC
