### ISSUE TITLE
How should you seed the Database with Roles?

### ISSUE THREAD

**Issue by janhartmann** [aspnet/Identity#911] opened 2016-07-15 12:18 UTC
Since EF Core does not yet support database seeding, I am creating my own set of abstractions to do it for me until then.

Apperently the `RoleManager<T>` throws and exception that I am accessing an disposed object on its `CreateAsync` method: 

``` cs
var result = _roleManager.CreateAsync(new IdentityRole<Guid> { Name = role }).Result;
```

> InnerException    {System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'RoleManager`1'.
>    at Microsoft.AspNetCore.Identity.RoleManager`1.ThrowIfDisposed()
>    at Microsoft.AspNetCore.Identity.RoleManager`1.<CreateAsync>d__30.MoveNext()}  System.Exception {System.ObjectDisposedException}

This is my `Startup.cs` which is just a simple Pure DI approach to create my database initializers:

``` cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<AuthDbContext>(builder => builder.UseSqlServer(_configuration.GetConnectionString("Default"))));

    services.AddIdentity<ApplicationUser, IdentityRole<Guid>>()
        .AddEntityFrameworkStores<AuthDbContext, Guid>()
        .AddDefaultTokenProviders();

    services.AddMvc();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    ConfigureAuth(app);
    InitializeContainer(app);

    app.UseStaticFiles();
    app.UseIdentity();
    app.UseMvcWithDefaultRoute();

    // Time to seed the database
    var initializer = new CompositeDatabaseInitializer(new IDatabaseInitializer[]
    {
        new AddDefaultRolesDatabaseInititalizer(app.ApplicationServices.GetRequiredService<RoleManager<IdentityRole<Guid>>>())  
    });

    initializer.Seed();
}
```

The implementations of the `IDatabaseInitializer` are:

``` cs
public interface IDatabaseInitializer
{
    int Order { get; }

    void Seed();
}

public class AddDefaultRolesDatabaseInititalizer : IDatabaseInitializer
   {
    private readonly RoleManager<IdentityRole<Guid>> _roleManager;

    public AddDefaultRolesDatabaseInititalizer(RoleManager<IdentityRole<Guid>> roleManager)
    {
        _roleManager = roleManager;
    }

    public int Order { get; } = 1;

    public void Seed()
    {
        using (_roleManager)
        {
            if (_roleManager.Roles.Any()) return;

            var roles = new[]
            {
                "Role1",
                "Role2"
            };

            foreach (var role in roles)
            {
                var result = _roleManager.CreateAsync(new IdentityRole<Guid> { Name = role }).Result;
                if (!result.Succeeded)
                {
                    throw new Exception("Error creating roles.");
                }
            }
        }

    }
}

public class CompositeDatabaseInitializer : IDatabaseInitializer
    {
    private readonly IEnumerable<IDatabaseInitializer> _databaseInitializers;

    public CompositeDatabaseInitializer(IEnumerable<IDatabaseInitializer> databaseInitializers)
    {
        _databaseInitializers = databaseInitializers;
    }

    public int Order { get; } = 0;

    public void Seed()
    {
        foreach (var databaseInitializer in _databaseInitializers.OrderBy(initializer => initializer.Order))
        {
            databaseInitializer.Seed();
        }
    }
}
```

Any suggestions on what I do wrong?

Thanks.

**Comment by HaoK** [comment] 2016-07-15 18:39
There are lifetime issues here, the RoleManager is scoped to the lifetime of the request, and it depends on a DbContext which is similarly scoped.  Hence the error about accessing a disposed object.  Caching the manager in your initializer is accessing it after its already been disposed

**Comment by janhartmann** [comment] 2016-07-16 10:29
Yes, that is correct. How would you solve the issue with the need for a seeding at startup?

**Comment by HaoK** [comment] 2017-02-27 19:09
Dupe of https://github.com/aspnet/Identity/issues/1065 which shows how you can use the UserManager at startup which is the same

**Closed by HaoK** 2017-02-27 19:09 UTC
Labels: needs-investigation, question
