### ISSUE TITLE
Account Lockout does not work in Beta4 Templates

### ISSUE THREAD

**Issue by rustd** [aspnet/Identity#455] opened 2015-04-29 09:52 UTC
Account is not locked out when a user enters invalid code during 2FA Login. Is this a bug in Identity?

**Comment by MikeSchlichting** [comment] 2015-05-23 18:54
I'm seeing a similar issue with account locking.  PasswordSignInAsync(shouldLockout: true ) is not setting user.LockoutEnabled = true until AFTER the user enters their password.  So lockout checking will not occur during the first factor authentication.  However, if the user enters their correct password during first factor authentication THEN user.LockoutEnabled is set to true and lockout checking will be enforced during second factor authentication.        

@rustd Did you pass a value of 'true' to PasswordSignInAsync()?  2FA locking works for me when I pass in true for shouldLockout, but lockout checking does not work during 1FA.  I can get 1FA locking to work by first calling UserManager.SetLockoutEnabledAsync(user, true) prior to the login attempt but I would expect locking to work when the shouldLockout parameter is set to true.

**Comment by HaoK** [comment] 2015-05-24 17:46
@MikeSchlichting PasswordSignInAsync should not be setting LockoutEnabled to true, the only thing that should be doing that would be when Creating the user if lockout is enabled by default:

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/UserManager.cs#L327

Its intentional that lockout is only enabled for the 2FA flow as that has a fairly limited amount of possibilities by default, while the default password settings were considered strong enough to not require lockouts by default (since its easy to turn it on explicitly with shouldLockout = true)

Can you clarify what behavior you are seeing exactly with what works and what doesn't?

**Comment by MikeSchlichting** [comment] 2015-05-24 21:22
@HaoK Sure thing

Expected behavior: Setting shouldLockout = true will enable locking.

Actual behavior: Setting shouldLockout = true only works when LockoutEnabled is also set to true. 

Steps to reproduce:
1.  File New Asp.Net Web App/ASP.Net 5 Preview Templates/Web Site
2.  Change shouldLockout : false to shouldLockout : true in AccountController/Login
3.  Run App
4.  Register a new login
5.  Logout
6.  Try to login with an invalid password several times.

Result: User is not locked out
 
I was expecting to be able to turn on locking by setting shouldLockout = true.  It looks like you must first enable locking by calling UserManager.SetLockoutEnabledAsync(user, true);  Can you verify if this is the intended design?

**Comment by HaoK** [comment] 2015-05-24 22:16
Yes shouldLockout has no effect if lockout is not enabled for the user. But by default users are created with lockout enabled.

**Comment by MikeSchlichting** [comment] 2015-05-25 03:31
@HaoK Thank you for the clarification.

**Comment by HaoK** [comment] 2015-05-25 03:58
@MikeSchlichting What bits are you using?  I'm assuming you are using Beta4 or later, and if so I want to close this bug out

**Comment by MikeSchlichting** [comment] 2015-05-25 04:50
Beta 4.  I'm ok with closing this out.

**Closed** 2015-05-25 05:47 UTC
