### ISSUE TITLE
MultiLanguage web sites and Identity Error Messages

### ISSUE THREAD

**Issue by gerardog** [aspnet/Identity#1021] opened 2016-11-08 22:51 UTC
Currently, we can create a new IdentityErrorDescriber and plug them into the pipeline while initializing the web site.

```
    services.AddIdentity<User, IdentityRole>()
            .AddErrorDescriber<CustomIdentityErrorDescriber>();
```

But, what if we have a multilanguage web site, and we need to match the correct language **per request**?

Why does the current IdentityErrorDescriber class does not allow to use external resource files? What if instead of providing a custom IdentityErrorDescriber per language we just find a way to inject a new Resource file to a single/unique/sealed IdentityErrorDescriber ?

**Comment by gerardog** [comment] 2016-11-08 22:56
Reading this https://github.com/aspnet/Identity/issues/991#issuecomment-256516328 just realized this may already be in the backlog. Feel free to close as dupe.

**Comment by blowdart** [comment] 2016-11-09 18:24
Dupe of #991 

:)

**Closed by blowdart** 2016-11-09 18:24 UTC
