### ISSUE TITLE
Is it possible getting all the roles of a user in a view?

### ISSUE THREAD

**Issue by gdoron** [aspnet/Identity#949] opened 2016-08-30 21:05 UTC
e.g.

	@User.GetAllRoles().Any(x => x.StartsWith("Vendor_")
?
I can store the role as a claim and get all the claims that start with {xxx} but that seems less feasible for my needs.

**Comment by blowdart** [comment] 2016-08-31 21:53
Dupe of #947

**Comment by HaoK** [comment] 2016-08-31 22:07
UserManager.GetRolesAsync(user) will return you all of the roles for the user.

**Closed by HaoK** 2016-08-31 22:07 UTC

**Comment by gdoron** [comment] 2016-09-01 06:02
@HaoK 

I managed to find this way which doesn't require DB queries:

	@User.Claims.Where(x=> x.Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/role")
	
Is there any disadvantages using it?

**Comment by HaoK** [comment] 2016-09-01 06:05
That should work fine
