### ISSUE TITLE
Multi-tenant / delegated login page

### ISSUE THREAD

**Issue by joshmouch** [aspnet/Identity#713] opened 2016-01-15 15:13 UTC
I have a multi-tenant environment.  When a user is not authenticated, I want to redirect the user to a login page specific to their client (e.g. /client/{blah}/Account/Login).

In Identity 2.0, I couldn't do this, so I just created a custom filter that inherited from AuthorizeAttribute and added it to the MVC global filters.  However, this doesn't seem to be working in Identity 3.0.  There's a lot more going on with Policies and Requirements and stuff.

I'm about to try inheriting from AuthorizationFilter, instead, which I believe will work, but just wanted to double check that I'm approaching this the right way.

Is there support for a delegated login page?  If not, can you consider adding it?

As far as I can tell, there's no way to pass a delegate to the Identity framework to determine what the login page is, correct?  It looks like the only thing the CookieAuthenticationMiddleware considers using is IdentityCookieOptions.LoginPath, which is a string and can't really be modified per-request.

I also found that you can do something like this:

````
app.UseCookieAuthentication(o =>
{
    o.LoginPath = "/area1/login1";
    o.AuthenticationScheme = "scheme1";
    //TODO: set other interesting properties if you want to
});

app.UseCookieAuthentication(o =>
{
    o.LoginPath = "/area2/login2";
    o.AuthenticationScheme = "scheme2";
    //TODO: set other interesting properties if you want to
});
````

````
[Authorize(ActiveAuthenticationSchemes = "scheme1")]
public IActionResult Test1()
{
    return Content("Test1");
}

[Authorize(ActiveAuthenticationSchemes = "scheme2")]
public IActionResult Test2()
{
    return Content("Test2");
}
````

But that isn't quite flexible enough since the AuthenticationSchemes are hard coded on the actions.  If I could somehow set the AuthenticationSchemes per-request, this *might* work.

**Comment by rustd** [comment] 2016-01-27 22:45
Duplicate of #266

**Closed by rustd** 2016-01-27 22:45 UTC
