### ISSUE TITLE
Cookie expiration time configured in `ConfigureApplicationCookie` ignored by Identity

### ISSUE THREAD

**Issue by B-Esmaili** [aspnet/Identity#1425] opened 2017-09-12 17:59 UTC
Here is my configuration for identity cookie :
```
services.ConfigureApplicationCookie(cfg =>
            {
                cfg.Cookie.Name = "application_ms_state";
                cfg.Cookie.Expiration = TimeSpan.FromDays(15);
                cfg.SlidingExpiration = true;
            });
```
![cookie](https://user-images.githubusercontent.com/9152515/30341168-4e958efc-980a-11e7-9c92-e24f24d5b4f1.png)

as you can see cookies is generated for 15 days but it expires in almost half an hour.could anyone clarify what is problem with my configuration?

**Comment by VahidN** [comment] 2017-09-12 18:48
Have you configured your server to store the cookie decryption keys permanently? if not, whenever the server restarts or the app pool restarts, your users will have to login again.
[More info](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#data-protection)

**Comment by B-Esmaili** [comment] 2017-09-13 11:28
I went through the documentation and did as mentioned but still i get logged out after 30minutes.

**Comment by natemcmaster** [comment] 2017-09-13 20:01
Can you try changing your code to this?
```
cfg.ExpireTimeSpan= TimeSpan.FromDays(15);
```

As mentioned in the xmldocs, Cookie.Expiration is ignored on CookieAuthenticationOptions.

https://github.com/aspnet/Security/blob/a53bf093a7d86b35e019c80515c92d7626982325/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs#L62

Possible duplicate of https://github.com/aspnet/Security/issues/1293

**Comment by B-Esmaili** [comment] 2017-09-14 05:03
I have done this as well but no luck.@natemcmaster could you give me a reference to code which checks for ticked expiration?

**Comment by B-Esmaili** [comment] 2017-09-14 15:20
I found the location in which check for expiration is done and figured out that the problem is ,identity checks every 30  minutes (bu default) to see if issued authentication ticked is valid, consequently it checks to see if the class which is implementing `UserStore<>` is implementing `IUserSecurityStampStore` (`UserManager.SupportsUserSecurityStamp` in following code) for that matter.

https://github.com/aspnet/Identity/blob/eb3ff7fc32dbfff65a1ba6dfdca16487e0f6fc41/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L223

and following is getter of `SupportsUserSecurityStamp`

https://github.com/aspnet/Identity/blob/e36e681d5477e8fc4de7cc46717bb73f5fe92a0b/src/Microsoft.Extensions.Identity.Core/UserManager.cs#L248

 As my `MembershipService` class which is implementing `IUserStroe` does not implement `IUserSecurityStampStore<>` thus after 30 min interval i end up with invalid security stamp and a null principal which == `SignOut`. this waa my bas story.

**Comment by natemcmaster** [comment] 2017-09-14 16:36
Ok, thanks for letting us know @B-Esmaili. We'll use aspnet/Security#1293 for further follow up on the Cookie.Expiration vs ExpireTimeSpan discussion.

**Closed by natemcmaster** 2017-09-14 16:36 UTC

**Comment by tiljanssen** [comment] 2018-07-16 17:21
I had the same problem. It took me quite some time to find out the cause. 

Shouldn't addIdentity() check whether the securityStampValidatorStore is supported, and if not, either throw or skip the registration of the validation?

**Comment by HaoK** [comment] 2018-07-16 17:23
Sure that's a reasonable suggestion, can you file a new issue asking for that improvement? its something we can consider for 2.2 as it would be very cheap @tiljanssen

**Comment by aguayUmbt** [comment] 2018-07-23 14:02
![asd](https://user-images.githubusercontent.com/39703106/43081074-2cd65eb2-8e5f-11e8-8333-ff1f37a37905.PNG)
I would like to extend my authentication duration to 1 day, but from what I've understood, it's logging out after 30minutes. If I set it to 1 minutes, it actually work.
I've consulted many topics regarding this matter but couldn't find an answer I could understand. Please help me with this, thanks.
