### ISSUE TITLE
Couldn't able to rename Identity tables

### ISSUE THREAD

**Issue by ganeshnj** [aspnet/Identity#841] opened 2016-05-27 23:02 UTC
### Steps to reproduce

- Create subclasses for each of Identity entities
- Change the default key type to int/int16/int32/Int64

```
public class ApplicationRole : IdentityRole<Int64>
{
    public string Description { get; set; }
}
public class ApplicationRoleClaim : IdentityRoleClaim<Int64>
{
}
public class ApplicationUser : IdentityUser<Int64>
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}
public class ApplicationUserClaim : IdentityUserClaim<Int64>
{
}
public class ApplicationUserLogin : IdentityUserLogin<Int64>
{
}
public class ApplicationUserRole : IdentityUserRole<Int64>
{
}
public class ApplicationUserToken : IdentityUserToken<Int64>
{
}

```

Startup.cs
 ```
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc();

    services.AddDbContext<CustomIdentityContext>(options =>
    {
        options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
    });

    services.AddIdentity<ApplicationUser, ApplicationRole>()
        .AddEntityFrameworkStores<CustomIdentityContext, Int64>()
        .AddDefaultTokenProviders();
}

```

- Add fluent API to change original table names

CustomIdentityContext.cs
```
protected override void OnModelCreating(ModelBuilder builder)
{
    base.OnModelCreating(builder);

    builder.Entity<ApplicationUser>().ToTable("Users");

    builder.Entity<ApplicationRole>().ToTable("Roles");

    builder.Entity<ApplicationUserRole>().ToTable("UserRoles");

    builder.Entity<ApplicationRoleClaim>().ToTable("RoleClaims");

    builder.Entity<ApplicationUserClaim>().ToTable("UserClaims");

    builder.Entity<ApplicationUserLogin>().ToTable("UserLogins");

    builder.Entity<ApplicationUserToken>().ToTable("UserTokens");
}
```

- Add migration and update the database

### The issue
I've been trying to customize the Identity entities with some additional attributes and key type. Everything is working fine except the table names. Strangely, I'm able to change names of Users and Roles tables but couldn't able to rename the rest (RoleClaim, UserClaim, UserLogin, UserRole, UserToken).

You can also find the original project at https://github.com/ganeshnj/CustomIdentity

### Further technical details

EF Core version: 1.0.0-preview1-final
Identity version: 1.0.0-rc2-final
Operating system: Windows 10 Home 10586.318
Visual Studio version: Visual Studio Professional 2015 14.0.25123.00 Update 2

**Comment by yuleyule66** [comment] 2016-05-31 13:50
I have the same problems

**Comment by blowdart** [comment] 2016-06-01 21:22
Is this a dupe of #780?

**Comment by jvelezc** [comment] 2016-06-03 06:44
I wrote an article with the latest version of dot net and asp net identity. 
https://medium.com/@goodealsnow/asp-net-core-identity-3-0-6018fc151b4#.qs0fs4t8q

**Comment by zigzag95** [comment] 2016-06-03 14:10
@jvelezc Ecxellent doc

**Comment by zigzag95** [comment] 2016-06-03 14:41
I have an FK in by business classes called InputUser allowing us to log and audit database updates.
This FK points Identity user table.
Do you think I'll get errors if I move identity tables to security schema?

**Comment by jvelezc** [comment] 2016-06-03 15:54
Entity framework will handle everything on the background. So no you should not get any issues. If you do hit me up!

**Comment by zigzag95** [comment] 2016-06-03 17:53
I need to add DateFrom, DateTo in usersroles and manage authorisations using policies.
For now, we added our own table userrole to manage that and I believe it will be very useful if we manage that using Identity.

**Comment by jvelezc** [comment] 2016-06-03 18:55
Well the good news is that:https://github.com/aspnet/Identity/commit/104f2161915b1a4e7d0013f3de3b8d9a212a5d27#diff-c72544a50eacab8ada8ca53f53daee15 once that is merge into the main branch you can just follow my article and do the same for the other classes.

**Comment by zigzag95** [comment] 2016-06-03 19:22
This is a good news as u said.
But once this PR merged do I have to update manually the Nuget version in my project.json?

**Comment by jvelezc** [comment] 2016-06-03 19:26
Well, once they release it I can tell you for sure... is hard to say. I tried to open the dev branch and check but it has over 300 errors for me. So I cant even fiddle with it.The errors are mostly about some library  rc3... probably internal nightly builds of dot net or something. RTM is the end of this month... so if this change does not make it you probably had to wait a huge amount of time.

**Comment by zigzag95** [comment] 2016-06-03 19:28
Do they have ci nightly builds?

**Comment by jvelezc** [comment] 2016-06-03 19:31
If you feeling adventerous: https://github.com/dotnet/cli right now i have 64 bit machine on windows so I can't even get the latest version because the build is failing.

**Comment by divega** [comment] 2016-06-03 19:32
The CI feed for the dev branch of ASP.NET is https://www.myget.org/F/aspnetcidev/api/v3/index.json.

**Comment by divega** [comment] 2016-06-03 19:33
Other feeds described at https://github.com/aspnet/Home/wiki/NuGet-feeds.

**Comment by jvelezc** [comment] 2016-06-03 19:56
Below are my compiler issues that are preventing me to fiddle  with the commit above. This is literally just downloading from git, cloning and trying to launch.  
![lastone](https://cloud.githubusercontent.com/assets/3653845/15791154/87a99bba-298a-11e6-8da0-39b01d15b881.png)

![contributebuthow](https://cloud.githubusercontent.com/assets/3653845/15791067/1064941a-298a-11e6-9c63-d8ed3872ebac.png)
![devbranchcan tcompile](https://cloud.githubusercontent.com/assets/3653845/15791068/1073130a-298a-11e6-920c-6da019626c19.png)

**Comment by zigzag95** [comment] 2016-06-03 20:02
1. They should not user RC3 (community standup)
2. I tried to do the same with EF but same errors (package restore failed)
3. I wonder if Msft is really playing open source (unable to build).

**Comment by smitpatel** [comment] 2016-06-03 21:21
To build from GitHub repo, you need
VS 2015 Update 2
.NET RC2 tooling
The compiler errors you are getting is because of incorrectly restored packages. Do a `git clean -xdf` in the repo and run `./build.cmd` from command line. That will download latest dotnet needed to build the repo, restore all the packages and build the solution using dotnet. Opening the solution in VS should work then.
To build repo from source code you don't need to configure any nuget feeds. The project has config file to do so.

**Comment by divega** [comment] 2016-06-03 21:30
+1 to everything @smitpatel said.

In case it helps, if you are hitting the same problems as I am, just unload the "samples" folder (right-click on it in the solution explorer and click on the "Unload projects in the solution folder"). Everything else builds for me.

Anyway, life in the bleeding edge is hard. I.e. the dev branch and feed is often broken because of cross-repro breaking changes, and in those cases you may need to wait until things get in a good state again.

Besides `git clean -xdf` another trick that is often needed is to clear up your loca NuGet package caches. If you have `nuget.exe` you can do `nuget locals -clear all` or alternatively you can delete the contents of these three directories:

%USERPROFILE%\.nuget\ 
%LOCALAPPDATA%\NuGet\v3-cache\ 
%LOCALAPPDATA%\NuGet\Cache\

**Comment by jvelezc** [comment] 2016-06-03 21:48
I removed the sample projects and I am able to compile the project. Thanks.

**Comment by divega** [comment] 2016-06-04 05:31
@HaoK do the samples work for you?

**Comment by HaoK** [comment] 2016-06-04 05:40
They did earlier this week (say Wed) yes, but I probably have packages that are a bit old.

**Comment by HaoK** [comment] 2016-06-04 05:43
But samples is what pulls in all the rest of the dependencies like MVC so its more likely to run into issues as a result.

**Comment by smitpatel** [comment] 2016-06-04 06:24
Found the issue
`samples\Interop4.5` is csproj based class library which uses `nuget.config` which has hardcoded package versions. Some of those doesn't exists on myget feed hence package restore fails and gives compilation errors because assemblies are not found.

**Comment by zigzag95** [comment] 2016-06-04 06:46
Apologies for Msft team.
I'm now able to build without samples
👍🏼

**Closed** 2016-06-30 05:46 UTC
