### ISSUE TITLE
Flaky test: TraditionalWebApplicationTests.CanPerform_IdToken_Flow 

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Identity#1648] opened 2018-02-23 00:20 UTC
This test currently has a 6% failure rate on release/2.1 for Windows.

```
======= Failed test run #1 ==========
Assert.Equal() Failure
Expected: OK
Actual:   InternalServerError
   at Microsoft.AspnetCore.Identity.Service.FunctionalTests.TraditionalWebApplicationTests.<CanPerform_IdToken_Flow>d__3.MoveNext() in C:\b\w\33bdfc1cae7b2a38\modules\Identity\test\Service.FunctionalTests\TraditionalWebApplicationTests.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
======= Failed test run #2 ==========
Assert.Equal() Failure
Expected: OK
Actual:   InternalServerError
   at Microsoft.AspnetCore.Identity.Service.FunctionalTests.TraditionalWebApplicationTests.<CanPerform_IdToken_Flow>d__3.MoveNext() in C:\b\w\33bdfc1cae7b2a38\modules\Identity\test\Service.FunctionalTests\TraditionalWebApplicationTests.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

http://aspnetci/project.html?tab=testDetails&testNameId=-4945557580194386605&projectId=Releases_21Public&buildTypeId=Releases_21Public_Win2012

cc @ryanbrandenburg @javiercn

**Comment by javiercn** [comment] 2018-02-23 07:22
I do believe this is related to another issue we are talking about in another issue. Does this fail on full framework and on Windows Server 2012?
https://github.com/aspnet/Identity/issues/1630

**Comment by natemcmaster** [comment] 2018-02-23 17:57
The most recent failure was Windows Server 2012 on .NET Core 2.1.

http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=411823&_focus=102467

**Comment by ryanbrandenburg** [comment] 2018-02-23 19:28
I'll tag future instances of this so that they show up in [this](http://aspnetci/httpAuth/app/rest/builds?locator=tag:InternalServerTokenFlow,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)) query.

**Comment by mkArtakMSFT** [comment] 2018-02-28 21:22
@javiercn, is this confirmed to be a dupe? If so, please close this. Thanks!

**Comment by Eilon** [comment] 2018-03-13 23:32
@javiercn do you have an update on this? 8 days since last action. Flaky tests are killing us.

**Comment by javiercn** [comment] 2018-03-15 23:25
I've skipped all the tests affected by this and created a test experiment for it to run on the CI and see if we can repro it:
#1686

**Comment by javiercn** [comment] 2018-03-15 23:27
I don't think there's more action for preview2 here (other than watch the CI) or skip any additional test if I missed any.

**Comment by Eilon** [comment] 2018-03-16 00:05
@javiercn sounds good, I moved this item to 2.1.0, but let's keep an eye on it.

**Comment by mkArtakMSFT** [comment] 2018-03-27 22:46
Moved it to `rc` milestone just to monitor and close then, if no reproes will be observed.

**Comment by javiercn** [comment] 2018-04-13 06:16
@mkArtakMSFT I'm moving this to MQ. I'll take care of them next week as they are not product related issues nor anything we're shipping

**Closed** 2018-10-23 22:39 UTC
Labels: 1 - Ready, PRI: 1 - Required, cost: XS, identity-service, task
