### ISSUE TITLE
Change IOptions<> to IOptionsSnapshot<>

### ISSUE THREAD

**Issue by VahidN** [aspnet/Identity#1085] opened 2017-01-25 10:15 UTC
`reloadOnChange` parameter on the `AddJsonFile` method has no effect on the strongly typed configuration `IOptions<>` and only `IConfigurationRoot` is automatically updated whenever the underlying `appsettings.json` file changes. In ASP.NET Core 1.1.0 `IOptionsSnapshot<>` has the same behavior.
[More info](http://andrewlock.net/reloading-strongly-typed-options-in-asp-net-core-1-1-0/  )
ASP.NET Core Identity uses `IOptions<>` everywhere. so it would ne nice to replace `IOptions<>` with `IOptionsSnapshot<>`  in this framework.

**Comment by RehanSaeed** [comment] 2017-02-01 12:14
What is the point of `IOptions<>`? I fully expected the reason for it's existence being the reloading ability. Why was `IOptionsSnapshot<>` created instead and what use is `IOptions<>` anymore? Why not just register the options type directly?

**Comment by blowdart** [comment] 2017-02-15 20:15
Dupe of https://github.com/aspnet/Options/issues/163

**Closed by blowdart** 2017-02-15 20:15 UTC
