### ISSUE TITLE
Flow rememberme option while Enabling/ Disabling two-factor authentication

### ISSUE THREAD

**Issue by rustd** [aspnet/Identity#399] opened 2015-03-12 02:27 UTC
In the current flow we have a todo
await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
```C#
 public async Task<IActionResult> EnableTwoFactorAuthentication()
        {
            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                await UserManager.SetTwoFactorEnabledAsync(user, true);
                // TODO: flow remember me somehow?
                await SignInManager.SignInAsync(user, isPersistent: false);
            }
            return RedirectToAction("Index", "Manage");
        }
```
In v2 we add this API 
```C#
await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
```
We should enable this scenario for v3

**Comment by HaoK** [comment] 2015-03-12 03:40
So the first half of the bug is correct, the part about SignInAsync is not.  

The issue is that for all of the actions on the manage controller, when we regenerate the application cookie via sign in, we have no way to tell what the state of remember me was.

**Comment by HaoK** [comment] 2015-03-12 03:40
This is a dupe of this https://github.com/aspnet/Identity/issues/185

**Closed by HaoK** 2015-03-12 03:40 UTC
