### ISSUE TITLE
No sample for Single Page Application?

### ISSUE THREAD

**Issue by matxhe** [aspnet/Identity#405] opened 2015-03-13 04:38 UTC
I want to migrate my MVC5 SPA to MVC6,but for Asp.net Identity 3 look like totally different from previous version.
Currently only have cookie-based sample,where I can get the token-based one so that I can make it clear.

Thanks!

**Comment by HaoK** [comment] 2015-03-13 21:45
Dupe of https://github.com/aspnet/Identity/issues/193

**Closed by HaoK** 2015-03-13 21:45 UTC
Labels: Samples
