### ISSUE TITLE
UserTore defined IdentityUser hard coded string but it sould be tkey

### ISSUE THREAD

**Issue by jvelezc** [aspnet/Identity#707] opened 2016-01-07 22:26 UTC
Currently: 
```
    public class UserStore<TUser> : UserStore<TUser, IdentityRole, DbContext> where TUser : IdentityUser<string>, new()
    {
        public UserStore(DbContext context, IdentityErrorDescriber describer = null);
    }
```
Proposal:
``` 
public class UserStore<TUser> : UserStore<TUser, IdentityRole, DbContext> where TUser : IdentityUser<Tkey>, new()
    {
        public UserStore(DbContext context, IdentityErrorDescriber describer = null);
    }
```
Why? Because if I define 
```
 public class ApplicationUser : IdentityUser<int>
```
I will subsequently not be able to use the userstore.

**Comment by rustd** [comment] 2016-01-13 22:13
Duplicate of https://github.com/aspnet/Identity/issues/585 which is tracking this.

**Closed by rustd** 2016-01-13 22:13 UTC
