### ISSUE TITLE
Unable to define Custom RoleClaim due to generic constraint

### ISSUE THREAD

**Issue by davidgoh** [aspnet/Identity#933] opened 2016-08-10 08:54 UTC
```
public abstract class UserStore<TUser, TRole, TContext, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken> : IUserLoginStore<TUser>, IUserStore<TUser>, IDisposable, IUserRoleStore<TUser>, IUserClaimStore<TUser>, IUserPasswordStore<TUser>, IUserSecurityStampStore<TUser>, IUserEmailStore<TUser>, IUserLockoutStore<TUser>, IUserPhoneNumberStore<TUser>, IQueryableUserStore<TUser>, IUserTwoFactorStore<TUser>, IUserAuthenticationTokenStore<TUser>
        where TUser : IdentityUser<TKey, TUserClaim, TUserRole, TUserLogin>
        where TRole : IdentityRole<TKey, TUserRole, IdentityRoleClaim<TKey>>
        where TContext : DbContext
        where TKey : IEquatable<TKey>
        where TUserClaim : IdentityUserClaim<TKey>
        where TUserRole : IdentityUserRole<TKey>
        where TUserLogin : IdentityUserLogin<TKey>
        where TUserToken : IdentityUserToken<TKey>
```

`where TRole : IdentityRole<TKey, TUserRole, IdentityRoleClaim<TKey>>`

Shouldn't it be TRoleClaim ? 

`where TRole : IdentityRole<TKey, TUserRole, TRoleClaim >`

**Comment by HaoK** [comment] 2016-08-10 10:20
Dupe of https://github.com/aspnet/Identity/issues/855

**Closed by HaoK** 2016-08-10 10:20 UTC
