### ISSUE TITLE
GenerateChangePhoneNumberTokenAsync too long!

### ISSUE THREAD

**Issue by seven1986** [aspnet/Identity#1494] opened 2017-11-06 08:33 UTC
I am use identity add a phone number, and generate an token, but when I send sms, the supplier told me the token it's too long! 

![image](https://user-images.githubusercontent.com/20808494/32431720-7f0b35c0-c30f-11e7-8873-d7b637c15451.png)

![image](https://user-images.githubusercontent.com/20808494/32431770-a8b9438a-c30f-11e7-9f12-9128f52f746d.png)

Could provide a method it can generate some  number code ?

**Comment by HaoK** [comment] 2017-11-06 22:23
Yeah this has been fixed in 2.0.3 and 2.1 nightly builds, dupe of https://github.com/aspnet/Identity/issues/1388

**Closed by HaoK** 2017-11-06 22:23 UTC
