### ISSUE TITLE
IdentityUserClaim and IdentityRoleClaim Id primary key assumes identity column

### ISSUE THREAD

**Issue by brockallen** [aspnet/Identity#1015] opened 2016-11-03 17:24 UTC
Both the `IdentityUserClaim` and `IdentityRoleClaim` have an `int Id` property for primary keys. When running with SqlServer these work fine because somehow in the creation of the SqlServer DB the schema knows that these are to be identity column types. But when running with Postgres under RDS (https://en.wikipedia.org/wiki/Amazon_Relational_Database_Service) the DB does not because there is no explicit configuration for this in `OnModelCreating`. This is what is looks like:

```
builder.Entity<TUserClaim>(b => 
            {
                b.HasKey(uc => uc.Id);
                b.ToTable("AspNetUserClaims");
            });
```

At runtime when trying to add a claim:

```
await mgr.AddClaimAsync(user, new Claim("name", "Jon Doe"));
```

I'm getting an exception at runtime saying that Id is not being set (presumably by the DB at insert time):

> {Npgsql.PostgresException: 23502: null value in column "Id" violates not-null constraint
   at Npgsql.NpgsqlConnector.<DoReadMessageAsync>d__6.MoveNext()

I'm wondering if `OnModelCreating` should have an additional:

```
b.Property(x => x.Id).ValueGeneratedOnAdd()
```

I assume this tells the DB schema to make the column an identity column?

**Comment by brockallen** [comment] 2016-11-03 17:59
FYI -- I added these two lines to my DbContext's `OnModelCreating`:

```
builder.Entity<IdentityUserClaim<string>>().Property(x => x.Id).ValueGeneratedOnAdd();
builder.Entity<IdentityRoleClaim<string>>().Property(x => x.Id).ValueGeneratedOnAdd();
```

And it seems to have helped. So again, seems like it would make sense to include these in the base implementation.

**Comment by divega** [comment] 2016-11-03 20:54
@haok can you remind me, if the user switches to an int TKey, do we also rely on SQL Server IDENTITY behavior for things to work?

**Comment by brockallen** [comment] 2016-11-03 20:56
Not sure if this is what you're asking, but these two classes I mention above have a hard coded `int Id` as the key regardless of the `TKey` used for the `IdentityUser<TKey>`.

**Comment by HaoK** [comment] 2016-11-03 21:10
Yeah looks like we have an implicit dependency on that IDENTITY behavior due to us picking int's for these.  Since we never set them and just assume that they get autoincremented

**Comment by divega** [comment] 2016-11-03 22:03
@brockallen yeah, I know it is different but I suspect if you switch `TKey` to be numeric the same can happen with the provider. BTW, what provider exactly (name and version) are you using?

@HaoK still not sure whether this is a problem. My expectation was that value generated on add would be set by convention for these properties, but I haven't looked at the code yet. Either the behavior is more provider specific than I thought or the particular provider Brock is using could be doing something that prevents it from happening.

**Comment by divega** [comment] 2016-11-03 22:06
BTW I expect some additional configuration to be necessary in `ApplicationDbContext` if you choose to use an EF/database provider that deviates from certain common behaviors, but I am just not sure yet if this particular case should be one of those.

**Comment by brockallen** [comment] 2016-11-04 00:21
> BTW, what provider exactly (name and version) are you using?

"Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.2"

> still not sure whether this is a problem in our code.

Well, it's an internal thing and for those who don't know how to read the source they'd get stumped I think. If it doesn't hurt the SqlServer scenario, then why would it hurt? I'm not sure it's fair to expect the provider code to infer the assumption simply based on the property name `Id`. What about any other `int` property? Is it a standard expectation in EF Core that an `ind Id` implies an identity column, or just the SqlServer side of that?

**Comment by divega** [comment] 2016-11-12 02:42
I had some time to look at this today again and it looks like it could be the result of an intentional change in the PostgreSQL provider (described in http://www.npgsql.org/news/efcore-1.1.0-preview1.html). It is a bit unfortunate and I would have expected this to work without any additional mapping but maybe there were other issues with that.

@roji any thoughts?

**Comment by roji** [comment] 2016-11-12 07:41
I'm not sure I entirely understand the issue (have little experience with ASP.Net Identity), but here are some thoughts.

If I understand things correctly, KeyDiscoveryConvention is the component responsible for identifying keys (i.e. automatically marking a property named `Id` as a Key). This is included in the core convention set which is used in Npgsql, so id properties should be identified there just like with SQL Server. I just confirmed this in an isolated test - properties called `Id` (and not explicitly marked with ValueGeneratedOnAdd) are properly created as PostgreSQL serial columns (which is kind of the equivalent of SQL Server IDENTITY). In other words, I think it's OK for ASP.NET Identity to depend on the behavior where properties named `Id` are automatically recognized as keys.

The change in 1.1.0-preview1 is unfortunate - it's because I misunderstood some important things when first writing the EF Core provider, and it was important to clean that up (and especially in order to add HiLo support). However, this issue doesn't mention 1.1.0 anywhere - it seems the issue is happening with 1.0.0. Regardless, the 1.1.0 issues should only bite people who already have migrations generated by the 1.0.0 provider - people starting fresh with 1.1.0-preview1 shouldn't experience any issues.

So I'm not really sure what's going on, and especially how explicitly adding `ValueGenerateOnAdd` resolves anything here. @brockallen if you can post a minimal code sample that reproduces the issue I could take a look.

**Comment by divega** [comment] 2016-11-15 21:27
@roji I probably just misunderstood what the Npgsl release notes meant about the ValueGeneratedOnAdd annotation. Agreed that the conventions should be sufficient here and that there seems to be a more subtle issue that needs understanding. 

@AndriySvyryd is going to help us investigate this issue.

**Comment by brockallen** [comment] 2016-11-15 21:39
Thanks for looking into it more -- I've not had time.

**Comment by roji** [comment] 2016-11-16 08:59
@divega OK no problem, I'll keep following this issue to see if I can help. If you have a repro I could look into it on my side too.

**Comment by AndriySvyryd** [comment] 2016-11-18 23:16
@brockallen It would be helpful to have a full repro for this.
Some of these type of issues should be fixed by https://github.com/aspnet/EntityFramework/pull/7044 as it will set ValueGenerated more consistently

**Comment by brockallen** [comment] 2016-11-20 16:03
IIRC all I did was create a new ASP.NET Core w/ ASP.NET Identity project, change the connection string to use PostgreSql, created the DB, created a user, and added a claim.

**Comment by ajcvickers** [comment] 2018-08-30 23:59
@brockallen I believe this should no longer be an issue with more recent versions of EF and the Npgsql provider. If that is not the case, please post a runnable project/solution or complete code listing that demonstrates the issue and we will re-open and investigate further.

**Closed by ajcvickers** 2018-08-30 23:59 UTC
Labels: needs-investigation
