### ISSUE TITLE
External logins breaking suddenly?

### ISSUE THREAD

**Issue by madmunsterdaddy** [aspnet/Identity#1005] opened 2016-10-22 23:59 UTC
I added Google, Microsoft, Twitter and Facebook as external auth providers. This all used to work great. Suddenly I'm finding it's not working as well (wondering if its one of the recent .NET Core patches?)

Here's what I'm noticing.

1) Create new ASP.net Web Application with Individual auth
2) Add and configure external providers
3) Register for a new account using a password then log on
4) Go to External Login Providers and add a new one (such as Twitter)
5) After its added, try to add another one

I am then redirected to this address, which is then a 404.
https://localhost:44377/Account/AccessDenied?ReturnUrl=%2FManage%2FLinkLoginCallback

I saw this in my own app, then created a brand new application and was able to reproduce there as well. Like I said, this didn't use to happen, it all used to be very smooth.

Any ideas at what's happening here?

**Comment by blowdart** [comment] 2016-10-26 21:16
Are you on RC2 or RTM? This sounds awfully like https://github.com/aspnet/Announcements/issues/201

**Comment by madmunsterdaddy** [comment] 2016-10-26 21:58
I'm in 1.0.1... so post-RTM?

I was bitten by that bug in RC... RTM corrected it. This is different. I've never seen this "accessdenied" action its trying to get it.

I believe it is new as of 1.0.1. I tried to revert, but still having the same issues.

**Comment by Ketrex** [comment] 2016-10-26 22:46
I am also experiencing this exact issue now when it was working previously. I can login using an external login provider just fine. When I attempt to add additional external logins to my account, I am redirected to the AccessDenied page. This functionality was working previously, probably before 1.0.1, though I cannot confirm.

**Comment by madmunsterdaddy** [comment] 2016-10-26 22:54
Yay! I'm happy its not just me. Solidarity! :D

I hit it when I was trying to implement IdentityServer4. Figured it was something goofy there but just couldn't figure out why. 4 hours later I tried it in my app that was known to previously work with RTM and then just built up a new app and was able to repro there as well.

**Comment by divega** [comment] 2016-10-26 23:00
@HaoK any other ideas?

**Comment by HaoK** [comment] 2016-10-26 23:20
Can you narrow down the timeframe between when it was working and when it stopped?  Did you upgrade versions?  

If External logins don't work in any app including new apps, can you also try on a different machine to confirm its not specific to something getting messed up on the machine.

**Comment by madmunsterdaddy** [comment] 2016-10-26 23:35
Well like I said it worked in RTM. I know because i was eager to test after removing the former RC2 workaround (which also doesn't work to fix this BTW). The only thing that happened since then was installing 1.0.1. My site is still in dev and not production yet so unfortunately I can't narrow down a timeline. I only noticed it this weekend. But it definitely WAS working.

Broken on my machine and when I published to Azure. Cleared cookies and all that stuff. Tried different browsers. Same result across the board.

**Comment by HaoK** [comment] 2016-10-26 23:41
This works fine for me right now against the identity sample so the underlying APIs are fine.  My guess is something in your app is causing this.

Try removing the change added in 1.0.1 to templates that is clearing the external cookie.

https://github.com/aspnet/Templates/commit/306fbc6b62c01a55c77399688ae57e11f3f6f359

**Comment by madmunsterdaddy** [comment] 2016-10-26 23:50
Hmmm.... I don't have that in the account controller :-|

**Comment by madmunsterdaddy** [comment] 2016-10-27 00:08
I added that code to my account controller. It didn't fix it.

**Comment by madmunsterdaddy** [comment] 2016-10-27 00:14
@HaoK can you attach the project you just made and I'll replace with my externals and see if I can repro there?

**Comment by jgimness** [comment] 2016-10-27 02:18
Same problem here too.  Immediately after the 2nd entry it redirects to /Account/AccessDenied?ReturnUrl=%2Faccount%2Fexternallogincallback

The last line called in AccountController is  
`return Challenge(properties, provider);`
https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.Mvc/Controllers/AccountController.cs#L151

Manually deleting the "Identity.External" cookie allows reentry.

**Comment by HaoK** [comment] 2016-10-27 02:24
Yeah so you guys have the opposite problem then, you need to add the line of code that was added in 1.0.1 to fix the issue, you are running into aspnet/Announcements#201

**Comment by madmunsterdaddy** [comment] 2016-10-27 02:31
I added that tonight with no effect. I'll debug through that login method tomorrow to see what that value is.

**Comment by jgimness** [comment] 2016-10-27 02:51
Just added and tested it right now, and it did not fix the problem.

**Comment by HaoK** [comment] 2016-10-27 04:30
Well if manually deleting the external cookie works, that fix is basically automating that for you, so it should accomplish the same thing as your manual fix.

**Comment by Ketrex** [comment] 2016-10-27 12:05
@HaoK, I think there is a disconnect here.

The issue is not with calling Account/ExternalLogin from the template, that works fine.
The problem occurs when calling Manage/LinkLogin to add a second external login to an existing (and currently logged in) account.
I can call Account/ExternalLogin with no problem with Facebook, Google, Twitter, and Microsoft, but trying to associate any additional external logins with that account now fails.

Correct me if I'm wrong @madmunsterdaddy or @jgimness but I believe that is the problem you're experience as well, right?

**Comment by madmunsterdaddy** [comment] 2016-10-27 13:19
Yes, Ketrex, that is exactly it.

Also, creating a new project doesn't add that revised template of the AccountController? I have installed DotNetCore.1.0.1-VS2015Tools.Preview2.0.2.exe and uninstalled any previous version of .NET Core. Is there another step that is required? Was that code added post 1.0.1?

**Comment by madmunsterdaddy** [comment] 2016-10-27 13:28
Video repro of the issue.
http://screencast.com/t/WsQDA97E9

**Comment by Ketrex** [comment] 2016-10-27 13:42
@madmunsterdaddy the problem isn't with the account controller (nor is the problem covered in any of these previous fixes. The problem appears to be in the ChallengeResult and how it responds to an attempt to add another external login to an already logged in account. The previous fixes definitely do not address this current scenario.

**Comment by jgimness** [comment] 2016-10-27 15:10
@Ketrex My variation is even with a non-logged in user.  For instance:

1. User goes to the login page
2. User clicks Login with Facebook
3. Whoops, they wanted to login with Google instead, so they click the Back button
4. Login panel (shown from browser cache), user clicks Google
5. User get the /Account/AccessDenied page

In #4, the "Identity.External" cookie is still hanging around, and not getting cleared out because the login page is served from browser cache.  Even if I add
`  // Clear the existing external cookie to ensure a clean login process
            await HttpContext.Authentication.SignOutAsync(_externalCookieScheme);` to the ExternalLogin callback, I can still reproduce the problem.

**Comment by Ketrex** [comment] 2016-10-30 15:30
@madmunsterdaddy, just fyi, I upgraded my project to 1.1.0-preview (not to be mistaken with 1.0.1), and it appears the problem has been corrected. I haven't had time to dig into the code to see what has changed but clearly the ASP.NET Core team knew this was an issue and the future release does fix it.

**Comment by madmunsterdaddy** [comment] 2016-10-30 15:36
Thanks @Ketrex -- I considered doing the same. Maybe I'll give it a go considering I'm not in production yet anyways.

**Comment by HaoK** [comment] 2016-11-07 20:07
Closing this bug, template issue will track this

**Closed by HaoK** 2016-11-07 20:07 UTC
