### ISSUE TITLE
DbContext in Separate Class Library

### ISSUE THREAD

**Issue by pettechbytes** [aspnet/Identity#920] opened 2016-07-25 04:13 UTC
This may sound elementary, but I am attempting to move my IdentityDbContext into a separate class library (as I did in MVC5) and am having trouble.  I was thinking about SoC, but when using Identity and Entity Framework, not sure how you can accomplish SoC fully.  My goal is to have a Data project that I can add migrations as the entities and relationships change over time.  I can't seem to get this to work in Core.

**Comment by arespr** [comment] 2016-07-25 16:46
I think EntityFramework DbContext should be separated from identity domain model classes like IdentityRoleClaim<TKey> that are used directly by dbcontext. I want to achieve possibility to replace entity framework by any other orm for example EF6, dapper or raw ado - by replacing only one dll and making a few configuration changes in Startup class.  I tried to imlement interfaces over dbcontext model classes but i failed because of inconsistent generic type constraints in RoleStore and UserStore classes.

**Comment by HaoK** [comment] 2016-07-25 18:09
Dupe of https://github.com/aspnet/Identity/issues/883

**Closed by HaoK** 2016-07-25 18:09 UTC

**Comment by donnienosa** [comment] 2018-08-30 10:36
I have the same problem or similar. I have been able to implement entity framework in a library but using a single instance of the context for all operations. I want to use the library for windows forms, wpf and web (including services) but some how i have not been able to get past the "object disposed error" (i have a method that reloads the context i.e disposes the context and recreates it for every select). I'm seriously confused on what to here because i don't want to expose the dbContext in the calling application
