### ISSUE TITLE
ID column to Int

### ISSUE THREAD

**Issue by LorenDorez** [aspnet/Identity#606] opened 2015-10-29 18:57 UTC
I am having an issue setting the ID column to an INT. I tried to follow the article posted here https://ericswann.wordpress.com/2015/03/14/nozus-step-3-adding-asp-net-identity-to-mvc-6/

However im having no success. I get an error message about "Cannot insert the value NULL into column 'Id', table 'Oversii.dbo.AspNetRoles'; column does not allow nulls. INSERT fails."

Some Code below

Startup.cs
```
    // Add Identity services to the services container.
            services.AddIdentity<ApplicationUser, ApplicationRole>()
                .AddEntityFrameworkStores<ApplicationDbContext, int>()
                .AddDefaultTokenProviders();
```

IdentityModel.cs
```
// Add profile data for application users by adding properties to the ApplicationUser class
    public class ApplicationUser : IdentityUser<int>
    {
    }
    public class ApplicationRole : IdentityRole<int>
    {
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, int>
    {
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }

        public DbSet<PropertyManagementCompany> PMC { get; set; }
    }
```

SampleData.cs
```
 public class SampleData
    {
        public static async Task InitializeIdentityDatabaseAsync(IServiceProvider serviceProvider)
        {
            using (var db = serviceProvider.GetRequiredService<ApplicationDbContext>())
            {
                //if (await db.Database.EnsureCreatedAsync())
                //{
                    await CreateAdminUser(serviceProvider);
                //}
            }
        }

        /// <summary>
        /// Creates a store manager user who can manage the inventory.
        /// </summary>
        /// <param name="serviceProvider"></param>
        /// <returns></returns>
        private static async Task CreateAdminUser(IServiceProvider serviceProvider)
        {
            const string adminRole = "Administrator";
            const string adminEmail = "Admin@test.com";
            const string adminPassword = "Admin123!";

            var userManager = serviceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var roleManager = serviceProvider.GetRequiredService<RoleManager<ApplicationRole>>();
            if (!await roleManager.RoleExistsAsync(adminRole))
            {
                await roleManager.CreateAsync(new ApplicationRole { Name = adminRole });
            }

            var user = await userManager.FindByNameAsync(adminEmail);
            if (user == null)
            {
                user = new ApplicationUser { UserName = adminEmail, Email = adminEmail };
                await userManager.CreateAsync(user, adminPassword);
                await userManager.AddToRoleAsync(user, adminRole);
                await userManager.AddClaimAsync(user, new Claim("ManageStore", "Allowed"));
            }
        }
    }
```

**Comment by slaneyrw** [comment] 2015-11-02 06:38
Doesn't appear you are setting the Id of the new IdentityUser instances.  The default implementation set's the string Id to a new Guid in the constructor

**Comment by msmaldi** [comment] 2015-11-22 13:35
Try use your code with `IdentityRole<int>` instead `ApplicationRole`
```csharp
public class ApplicationUser : IdentityUser<int>
    {
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser, IdentityRole<int>, int>
    {
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }

        public DbSet<PropertyManagementCompany> PMC { get; set; }
    }


services.AddIdentity<ApplicationUser, IdentityRole<int>>()
                .AddEntityFrameworkStores<ApplicationDbContext, int>()
                .AddDefaultTokenProviders();
```

**Comment by HaoK** [comment] 2016-03-31 21:46
Dupe of this https://github.com/aspnet/Identity/issues/780 which has working code

**Closed by HaoK** 2016-03-31 21:46 UTC
Labels: bug, question
