### ISSUE TITLE
Custom SignInManager

### ISSUE THREAD

**Issue by brentdavid2008** [aspnet/Identity#792] opened 2016-04-04 23:24 UTC
Hi,
Messing around with a .net core and identity in the MVC projects and i'm attempting to see how we'd use/re-create existing things we already do and how you might implement them.

First,
I see extension methods for .AddUserManager and .AddRoleManager, are there any plans to expose this to the sign in manager too?

I understand the reservations behind not exposing it, however, we would like to track the last login date of any particular user.  In previous generations i was simply inheriting from signinmanager<> and overriding the signinasync functions and after checking their results from base.signinasync, updating the value on the user property before returning back.

However, it doesn't look like i can actually register my own signinmanager.  Is this true? 

Second,
If this is true, is there a way for me to register/watch an event or something on the sign in manager that allows me to update values or make additional final decisions before allowing a user to sign in or validate?

I apologize if I missed this in another issue, searching 'signin' only came back with two results on the issues list.

Thanks for your help!
Brent

**Comment by brentdavid2008** [comment] 2016-04-04 23:35
Upon further looking i see #650 and #646 are apart of this too.

I personally think that the best approach is how the IdentityServer3 team (maybe that's you guys too) did their events.  So on the startup class, i can watch the return even and based on all the passed in information, i.e. SignInResult, or something execute my own project specific code.

the #650 sounds promising, but i'd never store just the time, and as a Company, we've decided to always have 'Utc' on the end of each of our property names if they're dates or 'local' if they're local dates.  Since everyone has their own conventions, I'd personally leave it up to the users to add their own properties and watch this event. 

However, should you choose to do #650 my vote would be adding all three as DateCreatedUtc, LastLoginDateUtc and LastActivityDateUtc (this property feels like i'd constantly be hitting the database, might want to leave that one out).

Just my two cents.  

Happy Coding,
Brent

**Comment by HaoK** [comment] 2016-05-02 03:14
I'm not exactly sure what the main issue with this bug is, but if its just about how to override SignInManager, you can just do `services.AddScoped<SignInManager<YourUser>, YourSignInManager>()` or the equivalent to ensure your custom sign in manager is used instead of the default one.

**Comment by divega** [comment] 2016-05-04 21:23
@brentdavid2008 does the last comment by @HaoK answer your question?

**Comment by brentdavid2008** [comment] 2016-05-04 21:27
it does, but i still would rather see it as one of the default .AddSignInManager(); functions to add my own type in the <> to be consistent with the rest of the methods that are .AddUserManager() and .AddRoleManager()

**Comment by divega** [comment] 2016-05-04 21:34
Thanks @brentdavid2008. I agree that would be a nice addition although it isn't high priority to do it so moving to backlog for now. 

cc @HaoK @blowdart

**Comment by HaoK** [comment] 2016-07-01 20:57
Dupe of https://github.com/aspnet/Identity/issues/565

**Closed by HaoK** 2016-07-01 20:57 UTC
