### ISSUE TITLE
AuthorizeAttribute and RoleStore.IsInRole method use separate methods to check role

### ISSUE THREAD

**Issue by artem-leonov** [aspnet/Identity#1117] opened 2017-02-28 08:37 UTC
AuthorizeAttribute checks role equality by name, but IsInRole method of UserStore checks role equality by normalized name. Example:
```
[Authorize(Roles = "manager")] // It's will be ok
public async Task<IActionResult> SomeMethod(...)
{
    var isInRole = await _roleStore.IsInRoleAsync(user, "manager", cancellationToken); // It's will be false!
    ...
}

[Authorize(Roles = "MANAGER")] // It's will be not ok
public async Task<IActionResult> SomeMethod(...)
{
    var isInRole = await _roleStore.IsInRoleAsync(user, "MANAGER", cancellationToken); // It's will be true!
    ...
}
```

I think there need some unification

**Comment by blowdart** [comment] 2017-03-01 18:38
@HaoK Oh dear. This needs changing, but it may break a bunch of folks

**Comment by HaoK** [comment] 2017-03-01 19:05
Normalization is an identity concept though today, unless we want to push that concept to Auth?

**Comment by divega** [comment] 2017-03-02 05:42
Curious, wasn't the purpose of normalization just to disallow users or roles to be created that could seem equivalent? Did we make an explicit decision that using it for other comparisons was ok?

**Comment by HaoK** [comment] 2017-03-02 07:11
Yes so for identity we are case insensitive, but the claim we generate for the role is the actual role name (not normalized).  The implementation in AuthZ uses IsInRole on ClaimsIdentity which is case sensitive.  Identity isn't involved on that side of things, we just generate the claim (via our UserClaimsPrincipalFactory), and we use the normalization service for our APIs, hence the difference in behavior.  RoleManager is case insensitive, but the AuthZ apis don't have any concept of normalization/case insensitivity for the role check

**Comment by HaoK** [comment] 2017-03-02 07:13
This would be the same issue for any of the other things we normalize, like user name, `UserManager.FindByName("WeirdCaPS") will be true, while Authorize("PolicyCheckingNameEqualsWEIRDCAPS") will be false just like the roles check.

Its not that bad though, since they can work around this by not using Roles = and adding a policy that did a case insensitive string equality check on the role claim instead of using the sugar method.

**Comment by artem-leonov** [comment] 2017-03-02 07:25
@HaoK but, as you can see in example, IsInRole method of UserStore is not case insensitive. It expected you pass already normalized role and that is a problem, I think

**Comment by HaoK** [comment] 2017-03-02 07:31
That is by design, identity is not case sensitive with roles name by default, its just like user name, we don't want them to be considered different.

**Comment by HaoK** [comment] 2017-03-02 07:32
What IS case sensitive is ClaimsIdentity.IsInRole https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authorization/Infrastructure/RolesAuthorizationRequirement.cs#L58

**Comment by HaoK** [comment] 2017-03-02 07:33
`Authorize(Roles = "foo")` ends up calling that, identity produces a claimsidentity with that claim, its decoupled from the authorization logic by that point

**Comment by artem-leonov** [comment] 2017-03-02 07:40
@HaoK I guess, it is little strange that I can't create "manager" and "MANAGER" roles in one app, but if I created "manager" role and then try to check that user is having "Manager" role - i will get "false". I believe, it is design lack.

**Comment by HaoK** [comment] 2017-03-02 07:49
Two different systems. you either need to use the same casing, or instead of using the built in Roles parameter, use a policy that has a requirement that checks the Role claim using a case insensitive comparison

```
services.AddAuthorization(options =>
{
    options.AddPolicy("ManagerRole", policy => policy.RequireAssertion(context => String.Equals("Manager", context.User.FindFirst(ClaimTypes.Roles).Value, StringComparision.OrdinalIgnoreCase));
});
```

**Comment by artem-leonov** [comment] 2017-03-02 07:56
@HaoK My fault, it was incorrect example. If I create "manager" role and then check user having "manager" role with UserStore - I will get "false" because UserStore.IsInRoleAsync method expect already normalized name. Shouldn't this method expect unnormalized role?

**Comment by HaoK** [comment] 2017-03-02 09:16
Oh that sounds like a bug yes

**Comment by HaoK** [comment] 2017-03-03 21:49
Actually I misread what you wrote, the basic idea is that the stores shouldn't have to deal with normalization, the manager will take care of dealing with making sure the names are normalized (or not), but its up to them, this allows the stores to just do simple equality checks.

Feel free to continue the discussion here, but things appear to be working by design here so I will close this issue

**Comment by HaoK** [comment] 2017-03-03 21:50
Generally you should never access the stores directly, you should always go through the manager APIs

**Closed by HaoK** 2017-03-03 21:49 UTC

**Comment by artem-leonov** [comment] 2017-03-04 13:13
@HaoK Ok, thank you
