### ISSUE TITLE
a serious bug in UserCore

### ISSUE THREAD

**Issue by richerp** [aspnet/Identity#890] opened 2016-06-30 08:49 UTC
public abstract class UserStore〈TUser, TRole, TContext, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken〉
.............................
    where TRole：IdentityRole〈TKey, TUserRole, IdentityRoleClaim〈TKey〉〉
 ............................

error:     where TRole ： IdentityRole 〈TKey, TUserRole, IdentityRoleClaim〈TKey〉
correct:  where TRole ： IdentityRole 〈TKey, TUserRole, TRoleClaim〉 ?

**Comment by richerp** [comment] 2016-06-30 08:54
public abstract class UserStore<TUser, TRole, TContext
.....
where TRole : IdentityRole<TKey, TUserRole, IdentityRoleClaim<TKey>>

is it where TRole : IdentityRole<TKey, TUserRole, TRoleClaim>????

**Comment by HaoK** [comment] 2016-06-30 09:57
Can you clarify what you are asking?

**Comment by richerp** [comment] 2016-06-30 12:29
error: where TRole ： IdentityRole 〈TKey, TUserRole, IdentityRoleClaim〈TKey〉
correct: where TRole ： IdentityRole 〈TKey, TUserRole, TRoleClaim〉 ?

**Comment by HaoK** [comment] 2016-06-30 20:49
Ah yes, dupe of https://github.com/aspnet/Identity/issues/855

**Closed by HaoK** 2016-06-30 20:49 UTC
