### ISSUE TITLE
How to add column to AspNetRoleClaims I cant register  IdentityRoleClaim via constructor to add more fields

### ISSUE THREAD

**Issue by jvelezc** [aspnet/Identity#683] opened 2015-12-17 16:45 UTC
My main issue: I want to add a property to IdentityRoleClaim called description. 
Why? So that when I build the front end I can display friendly text as to what the claim is all about. 

My current work around: I basically extended the role and have to map it to my CustomIdentityRoleClaim. My dba's are complaining....
```
 public  ICollection<CustomIdentityRoleClaim<TKey>> Claims { get;set; } ;

```
Before asp.net identity 2 I was able to pass a little bit more information that would have helped me customized my tables.
```   
public class IdentityDbContext<TUser, TRole, TKey, TUserLogin, TUserRole, TUserClaim> : DbContext
        where TUser : IdentityUser<TKey, TUserLogin, TUserRole, TUserClaim>
        where TRole : IdentityRole<TKey, TUserRole>
        where TUserLogin : IdentityUserLogin<TKey>
        where TUserRole : IdentityUserRole<TKey>
        where TUserClaim : IdentityUserClaim<TKey>
    {...
```
Today 
```
  public class IdentityDbContext : IdentityDbContext<IdentityUser, IdentityRole, string> { }
```
Which allows me to declare my own types of IdentityUser + IdentityRole very nice
```
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole,string>
//Which basically inherit from it and add more properties
public class ApplicationUser : IdentityUser<string>
    {
        public int CustomProperty { get; set; }
        public ApplicationUser() {
         
        }
  
    }
    public class ApplicationRole : IdentityRole<string>
    {
      
       
       
        public ApplicationRole()
        {
          
            this.Id = Guid.NewGuid().ToString();
        }

        public ApplicationRole(string name)
            : this()
        {
            this.Name = name;
        }

        public string Description { get; set; }
        // Add any custom Role properties/code here
    }
 
```
But what happened to public class IdentityRoleClaim<TKey> where TKey : IEquatable<TKey> namely why can't I inject my own NOTICE the IdentityRoleClaim

I would suggest the following 
```
  public class IdentityDbContext : IdentityDbContext<IdentityUser, IdentityRole, string,IdentityRoleClaim > { }


```
Besides downloading your source and adding a property to IdentityRoleClaim I don't see a way to add to a new property to the field.

**Comment by mdmoura** [comment] 2015-12-18 19:03
Same problem here ... Where is the option:
    
    public class IdentityDbContext : IdentityDbContext<IdentityUser, IdentityRole, string, IdentityUserLogin, IdentityUserRole, IdentityUserClaim>

**Comment by jvelezc** [comment] 2015-12-23 23:01
Please add this pull request !https://github.com/aspnet/Identity/pull/643

**Comment by rustd** [comment] 2016-01-13 22:22
Duplicate of #585

**Closed by rustd** 2016-01-13 22:22 UTC
