### ISSUE TITLE
Identity Token Expiration In ASP NET Core

### ISSUE THREAD

**Issue by chassq** [aspnet/Identity#999] opened 2016-10-19 19:45 UTC
Hey,

Can anyone point us to the documentation where it specifies hoe to control the default token provider expiration? We would like to extend this expiration timeout if possible. Here is a sample of our current service config:

            services.AddIdentity<ApplicationUser, IdentityRole>(
                options => {

                    options.Cookies.ApplicationCookie.AuthenticationScheme = "ApplicationCookie";
                    options.Cookies.ApplicationCookie.CookieName = "<some name>";
                    options.Cookies.ApplicationCookie.ExpireTimeSpan = TimeSpan.FromMinutes(SettingsProviderApp.AuthCookieExpiresInMinutes);
                })
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

Would we have to override the default token providers? If so are there any examples of this?

We are referencing:
    "Microsoft.AspNetCore.Identity": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",

Any help much appreciated!

Thanks!

**Comment by blowdart** [comment] 2016-10-26 21:29
Dupe of https://github.com/aspnet/Identity/issues/859

**Closed by blowdart** 2016-10-26 21:29 UTC

**Comment by cbettero** [comment] 2017-08-23 16:13
No, it's not the duplicate of #859,
we have the same problem: even if we set the ExpireTimeSpan like this:

`options.Cookies.ApplicationCookie.ExpireTimeSpan = TimeSpan.FromMinutes(120);`
the authentication seems to expire, randomly, after about 20 minutes.

What can be the problem ?
We are running ASP.NET Core 1.1 on IIS.

Thanks

**Comment by groege** [comment] 2017-12-14 09:35
We have the same problem in my company and think it is the worker process lifetime.
It seems like after 20 minutes the worker is killed (if not used)... should the token not be valid even if the worker has been killed?
Maybe someone can verify? Because we may be wrong.
