### ISSUE TITLE
why identity use user name to login in

### ISSUE THREAD

**Issue by diymine** [aspnet/Identity#1759] opened 2018-04-17 08:27 UTC
When I call the register code of identity to register a user, the code will update the normal name and user name same, and after I alter the user name, then re-login the system with email address, my login will fail,
It seemed identity logined by username not email, so why identity use user name to login in?

**Comment by diymine** [comment] 2018-04-17 08:27
or my understanding is wrong?

**Comment by blowdart** [comment] 2018-04-17 16:15
No you're right. The templates end up with username and email being the same during registration, but fail to keep them in sync. There's work scheduled for 2.2 to fix this ugly mess.

Dupe of https://github.com/aspnet/Identity/issues/1721

**Closed by blowdart** 2018-04-17 16:15 UTC

**Comment by diymine** [comment] 2018-04-27 01:33
I find a way to login user by email, first get the user by email, then call login method by PasswordSignInAsync(TUser user, string password, bool isPersistent, bool lockoutOnFailure) method
