### ISSUE TITLE
Preserve/Copy/Transfer Claims received during external authentication to the "Identity.Application" Identity

### ISSUE THREAD

**Issue by gabosistvanpwc** [aspnet/Identity#1529] opened 2017-12-12 14:23 UTC
Hi,

I need a way to preserve the claims received from the external identity provider when using the WsFederation authentication scheme. 

The claims received after a successful authentication with the external Identity Provider can not be found in the new "Identity.Application" identity created by the SignInManager.ExternalLoginSignInAsync method.

I'm using the basic ASP.NET Core Web Application project template with the Individual User Accounts authentication option. The WsFederation middleware is configured as follows:

services.AddAuthentication()
            .AddWsFederation(options =>
                {
                    options.Wtrealm = "xxxx";
                    options.MetadataAddress = "xxxx";                    
                })
            .AddCookie();

Thank you

**Comment by HaoK** [comment] 2017-12-14 20:40
Dupe of https://github.com/aspnet/AuthSamples/issues/6

**Closed by HaoK** 2017-12-14 20:40 UTC
