### ISSUE TITLE
Sliding Expiration Cookie does NOT set domain correctly

### ISSUE THREAD

**Issue by MarkPerryBV** [aspnet/Identity#1051] opened 2016-12-12 12:45 UTC
I am using the asp.net core identity with the following settings:
```
services.Configure<IdentityOptions>(options => {
  options.Cookies.ApplicationCookie.LoginPath = new PathString("/");
  options.Cookies.ApplicationCookie.SlidingExpiration = true;
  options.Cookies.ApplicationCookie.ExpireTimeSpan = TimeSpan.FromMinutes(20);
  options.Cookies.ApplicationCookie.AuthenticationScheme = "Microsoft.AspNetCore.Identity.Application";
  options.Cookies.ApplicationCookie.CookieDomain = Configuration["CookieConfig:Domain"];
});
```

When the user logs in I get a correct "Session" cookie set as follows:
![image](https://cloud.githubusercontent.com/assets/10271490/21099846/656d1c14-c068-11e6-99b0-4b0422e56be6.png)

This correctly set the `domain` property of the cookie.

I then leave my browser open for 10 mins and refresh the secure page.

This then happens:

![image](https://cloud.githubusercontent.com/assets/10271490/21099873/96af5a6c-c068-11e6-8ece-e0b5ef6c4232.png)

As you can see I now have two cookies. One with a domain specified and one without. This has the effect that now I can click the "signout" link using `signInManager.SignOutAsync()` and it will only remove the cookie with the domain set for it. The other auth cookie remains and allows the user to remain logged in. (until the browser window is closed).

Any ideas?

**Comment by HaoK** [comment] 2016-12-15 19:44
This appears to be a dupe of https://github.com/aspnet/Security/issues/991

**Closed by HaoK** 2016-12-15 19:44 UTC
Labels: needs-investigation
