### ISSUE TITLE
[bug].net core 2.1,Identity will throw exception while implement IdentityUser. But .net core 2.0 is Ok.

### ISSUE THREAD

**Issue by blowdart** [aspnet/Identity#1872] opened 2018-07-11 17:23 UTC
_From @Caizhenyu on July 7, 2018 11:58_

I am using asp net core Identity Framework on core 2.1, and I implement my  `ApplicationUser : IdentityUser` .Then there will throw Exception like the screenshot .
But I found that, the same code is Ok on core 2.0, or I just user IdentityUser not my own ApplicationUser is also ok while `services.AddIdentity<TUser, TRole>`.

Is it's a core 2.1 bug?
![tim 20180707194836](https://user-images.githubusercontent.com/19528235/42410678-1fcd9ff0-8220-11e8-9bf7-27d4c34b266a.png)

_Copied from original issue: aspnet/Security#1804_

**Comment by brockallen** [comment] 2018-07-11 17:53
Sounds like a DI config bug. Normally `AddIdentity<CustomUser>` would add the `UserManager<CustomUser>`

**Comment by Caizhenyu** [comment] 2018-07-12 02:00
@brockallen ,so ,i think it's maybe a bug

**Comment by HaoK** [comment] 2018-07-12 18:06
What's startup look like?

**Comment by Caizhenyu** [comment] 2018-07-13 01:41
@HaoK, nothing special.
`ApplicationUser : IdentityUser`

`ConfigureServices:
services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();`

`Configure:
app.UseAuthentication();`

you can rebuild it 3min.

**Comment by tstivers1990** [comment] 2018-07-26 03:49
@Caizhenyu Any chance you could create a repo that reproduces this issue? I'm not experiencing this myself, and my code looks very similar to what's shown here.

**Comment by HaoK** [comment] 2018-08-27 17:33
Closing due to lack of repro

**Closed by HaoK** 2018-08-27 17:33 UTC
Labels: needs-investigation
