### ISSUE TITLE
User Roles not being added as Role Type claims on sign in (Identity Core) (Bug? / User Error?)

### ISSUE THREAD

**Issue by cryptotrain** [aspnet/Identity#1997] opened 2018-10-08 07:07 UTC
Hello,
I believe I may have found a bug or I simply have a configuration issue, but after trolling through the MSDN Documentation for a couple of days and testing/trying, I cannot seem to figure this out.

My StackOverflow Question: https://stackoverflow.com/questions/52686139/asp-net-core-2-1-identitycore-role-claims-not-being-added-on-user-sign-in

I'm using **ASP.Net Core 2.1** with **IdentityCore Service**, the application is a pure API, no views at all. For authentication I'm purely using **Steam authentication** (No User/Pass login) provided by, https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers

**The problem** is that when I add a Role to a user (I've already got roles seeded and I've added my own steam account to the Admin Role), the role type claims are not being added on login, therefore when an admin user attempts to access an API route protected by [Authorize(Roles = "Admin") I'm being returned an Unauthorized Redirect.

Below I have added all code snippets I think is required (feel free to request more).

If I use (I am currently using this as a temporary solution, but it is not ideal for future development);

    services.AddIdentity<User, Role>()
       .AddEntityFrameworkStores<RSContext>()
       .AddSignInManager<SignInManager<User>>()
       .AddRoleManager<RoleManager<Role>>()
       .AddDefaultTokenProviders();

The application correctly adds the role claims on user sign in (and the Authorize attributes work), using all existing code from AuthController.cs, yet using IdentityCore it fails.

**NOTE:** The API will **correctly authenticate** and set the users cookies on sign in, but does not add the users roles to the users identity claims. Therefore, Authentication is Working, Authorization is not. If I utilise the [Authorize] attribute without specifying a Role it works flawlessly and only allows Authenticated users to access the route whilst denying unAuthenticated users. This can be seen in the Testing Screenshot at the end, identities[0].isAuthenticated = True, but the admin role is not being added to the Identity's Claims. As noted above, if I do not use AddIdentityCore and use AddIdentity, the roles are added to the user's claims correctly and the [Authorize(Role = "Admin")] attribute will work as expected, only allowing users that are apart of the Admin role to access it.

Startup.cs (Omitted irrelevant parts, eg. Database Connection)

    public void ConfigureServices(IServiceCollection services)
    {
        IdentityBuilder builder = services.AddIdentityCore<User>(opt =>
        {
            opt.Password.RequireDigit = true;
            opt.Password.RequiredLength = 6;
            opt.Password.RequireNonAlphanumeric = true;
            opt.Password.RequireUppercase = true;
            opt.User.AllowedUserNameCharacters += ":/";
        });

        builder = new IdentityBuilder(builder.UserType, typeof(Role), builder.Services);
        builder.AddEntityFrameworkStores<RSContext>();
        builder.AddSignInManager<SignInManager<User>>();
        builder.AddRoleValidator<RoleValidator<Role>>();
        builder.AddRoles<Role>();
        builder.AddRoleManager<RoleManager<Role>>();
        builder.AddClaimsPrincipalFactory<UserClaimsPrincipalFactory<User>>();
        builder.AddDefaultTokenProviders();

        services.AddAuthentication(options =>
        {
            options.DefaultScheme = IdentityConstants.ApplicationScheme;
            options.DefaultChallengeScheme = IdentityConstants.ApplicationScheme;
            options.DefaultAuthenticateScheme = IdentityConstants.ApplicationScheme;
            options.DefaultSignInScheme = IdentityConstants.ApplicationScheme;
            options.DefaultSignOutScheme = IdentityConstants.ApplicationScheme;
            options.DefaultForbidScheme = IdentityConstants.ApplicationScheme;
        })
            .AddSteam(options =>
            {
                options.ApplicationKey = Configuration.GetSection("Authentication:Steam:Key").Value;
                options.CallbackPath = "/api/auth/steam/callback";
                options.Events.OnAuthenticated = OnClientAuthenticated;
            })
            .AddIdentityCookies(options =>
            {
                options.ApplicationCookie.Configure(appCookie =>
                {
                    appCookie.Cookie.Name = "RaidSimulator";
                    appCookie.LoginPath = "/api/auth/login";
                    appCookie.LogoutPath = "/api/auth/logout";
                    appCookie.Cookie.HttpOnly = true;
                    appCookie.Cookie.SameSite = SameSiteMode.Lax;
                    appCookie.Cookie.IsEssential = true;
                    appCookie.SlidingExpiration = true;
                    appCookie.Cookie.Expiration = TimeSpan.FromMinutes(1);
                    appCookie.Cookie.MaxAge = TimeSpan.FromDays(7);
                });
                options.ExternalCookie.Configure(extCookie =>
                {
                    extCookie.Cookie.Name = "ExternalLogin";
                    extCookie.LoginPath = "/api/auth/login";
                    extCookie.LogoutPath = "/api/auth/logout";
                    extCookie.Cookie.HttpOnly = true;
                    extCookie.Cookie.SameSite = SameSiteMode.Lax;
                    extCookie.Cookie.IsEssential = true;
                    extCookie.Cookie.Expiration = TimeSpan.FromMinutes(10);
                });
            });
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, RoleManager<Role> roleManager)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        RolesSeed.Seed(roleManager).Wait();

        app.UseCors();
        app.UseAuthentication();
        app.UseMvc();
    }

    // Responsible for storing/updating steam profile in database
    private async Task OnClientAuthenticated(OpenIdAuthenticatedContext context)
    {
        var rsContext = context.HttpContext.RequestServices.GetRequiredService<RSContext>();
        var userManager = context.HttpContext.RequestServices.GetRequiredService<UserManager<User>>();

        var profile = context.User?.Value<JObject>(SteamAuthenticationConstants.Parameters.Response)
                            ?.Value<JArray>(SteamAuthenticationConstants.Parameters.Players)?[0]?.ToObject<SteamProfile>();

        // TODO: Handle this better, Redir user to an informative error page or something
        if (profile == null)
            return;

        var dbProfile = await rsContext.SteamProfiles.FindAsync(profile.SteamId);
        if (dbProfile != null)
        {
            rsContext.Update(dbProfile);
            dbProfile.UpdateProfile(profile);
            await rsContext.SaveChangesAsync();
        }
        else
        {
            await rsContext.SteamProfiles.AddAsync(profile);
            await rsContext.SaveChangesAsync();
        }
    }

AuthController.cs => The only code responsible for authenticating against the Identity.Application scheme

    [HttpGet("callback")]
    [Authorize(AuthenticationSchemes = "Steam")]
    public async Task<IActionResult> Callback([FromQuery]string ReturnUrl)
    {
        ReturnUrl = ReturnUrl?.Contains("api/") == true ? "/" : ReturnUrl;

        if (HttpContext.User.Claims.Count() > 0)
        {
            var provider = HttpContext.User.Identity.AuthenticationType;
            var nameIdentifier = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var name = HttpContext.User.FindFirstValue(ClaimTypes.Name);

            var loginResult = await signInManager.ExternalLoginSignInAsync(provider, nameIdentifier, false);
            if (loginResult.Succeeded)
            {
                return Redirect(ReturnUrl ?? "/api/auth/claims");
            }

            var result = await userManager.CreateAsync(new User { UserName = nameIdentifier, SteamId = nameIdentifier.Split("/").Last() });
            if (result.Succeeded)
            {
                var user = await userManager.FindByNameAsync(nameIdentifier);
                var identity = await userManager.AddLoginAsync(user, new UserLoginInfo(provider, nameIdentifier, name));

                if (identity.Succeeded)
                {
                    await signInManager.ExternalLoginSignInAsync(provider, nameIdentifier, false);
                    return Redirect(ReturnUrl ?? "/api/auth/claims");
                }
            }
        }

        return BadRequest(new { success = false });
    }

    [HttpGet("claims")]
    [Authorize]
    public async Task<IActionResult> GetClaims()
    {
        var user = await userManager.GetUserAsync(User);
        var claims =
            User.Claims.Select(c => new
            {
                c.Type,
                c.Value
            });

        var inAdmin = new string[] {
            "User.IsInRole(\"Admin\") = " + User.IsInRole("Admin"),
            "User.IsInRole(\"ADMIN\") = " + User.IsInRole("ADMIN"),
            "User.IsInRole(\"admin\") = " + User.IsInRole("admin"),
            "userManager.IsInRoleAsync(user, \"admin\") = " + await userManager.IsInRoleAsync(user, "admin")
        };

        return Ok(new { success = true, data = new { claims, inAdmin, User.Identities } });
    }

RoleSeeder.cs

    public static async Task Seed(RoleManager<Role> roleManager)
    {
        // Developer Role
        if(!await roleManager.RoleExistsAsync("Developer"))
        {
            var role = new Role("Developer");
            await roleManager.CreateAsync(role);
        }
        // Community Manager Role
        if (!await roleManager.RoleExistsAsync("Community Manager"))
        {
            var role = new Role("Community Manager");
            await roleManager.CreateAsync(role);
        }
        // Admin Role
        if (!await roleManager.RoleExistsAsync("Admin"))
        {
            var role = new Role("Admin");
            await roleManager.CreateAsync(role);
        }
        // Moderator Role
        if (!await roleManager.RoleExistsAsync("Moderator"))
        {
            var role = new Role("Moderator");
            await roleManager.CreateAsync(role);
        }
    }

Testing Screenshot: https://i.stack.imgur.com/oarHT.png

**Comment by HaoK** [comment] 2018-10-08 07:51
Yeah this has been fixed in 2.2, this is a dupe of https://github.com/aspnet/Identity/issues/1813

**Closed by HaoK** 2018-10-08 07:51 UTC
