### ISSUE TITLE
Login doesn't show registered social logins after error

### ISSUE THREAD

**Issue by wpqs** [aspnet/Identity#2074] opened 2018-11-19 06:02 UTC
I'm using ASPNET Core 2.1 with Razor Pages UI Library and noticed that whilst registered social logins appear when I open the Login page, they disappear after an error like incorrect password.

There seems to be a bug in Identity\Pages\Account\Login.cshtml.cs as 
````
 public IList<AuthenticationScheme> ExternalLogins { get; set; }

````
is only initialised in OnGetAsync(), but if an error happens OnPostAsync() then Page() is returned so OnGetAsyn() doesn't get called. Changing error handling in  OnPostAsync() so RedirectToPage() is returned seems to fix the problem.

Please confirm this is a bug and comment on my fix

**Comment by blowdart** [comment] 2018-11-19 12:16
Dupe of https://github.com/aspnet/Identity/issues/1636

**Closed by blowdart** 2018-11-19 12:16 UTC
