### ISSUE TITLE
RoleManager should provide List methods

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Identity#947] opened 2016-08-30 17:54 UTC
Having to rely on IQueryable to list roles means the store has to implement it, but it's an optional service, which means listing users is optional. 
I'd suggest to make it mandatory at the RoleManager level as the first thing you need to do when managing roles is to list them. To add some argument, there is a mandatory `FinById` but how do I get the Id in the first place?

I understand there are different levels of implementations: filtering, sorting, paging. Maybe provide a `GetRoles` at least, and then optional interfaces to do more, like the `IQueryableStore` but without the requirement of implementing `IQueryable` which is a loose contract.

**Comment by HaoK** [comment] 2017-01-18 18:17
Dupe of https://github.com/aspnet/Identity/issues/765

**Closed by HaoK** 2017-01-18 18:17 UTC
