### ISSUE TITLE
How to override the default (1 day) TokenLifeSpan?

### ISSUE THREAD

**Issue by gdoron** [aspnet/Identity#959] opened 2016-09-12 12:31 UTC
Hi,

After a lot of internal code reading... we found out that Identity is using a LifeSpan of 1 day, we need to change it, what's the way of doing it in core ?

**Comment by HaoK** [comment] 2016-09-14 18:02
Dupe of https://github.com/aspnet/Identity/issues/859

**Closed by HaoK** 2016-09-14 18:02 UTC
