### ISSUE TITLE
Social auth in infinite loop with cookie consent

### ISSUE THREAD

**Issue by natelaff** [aspnet/Identity#2011] opened 2018-10-15 20:15 UTC
I have a 2.1 app that isn't too far outside the standard identity code. 

I configure my cookie like so:

            services.ConfigureApplicationCookie(options =>
            {
                options.AccessDeniedPath = "/Account/AccessDenied";
                options.Cookie.Name = "sitenameishere";
                options.Cookie.HttpOnly = true;
                options.ExpireTimeSpan = TimeSpan.FromMinutes(60);
                options.LoginPath = "/Account/Login";
                options.LogoutPath = "/Account/Logout";
                options.ReturnUrlParameter = CookieAuthenticationDefaults.ReturnUrlParameter;
                options.SlidingExpiration = true;
            });

On my iPhone (I can't reproduce this on PC), after I have logged in with facebook, then it logs me out after some expiration time, when I try to log on again I get stuck in a loop with the cookie consent banner popping up. so that banner will popup, I accept, log on with facebook again, then it just takes me right back there. if I clear cookies from the mobile browser (be it safari, edge or chrome), it will work and let me log on... but eventually starts the same thing again.

**Comment by blowdart** [comment] 2018-10-25 18:07
Dupe of https://github.com/aspnet/Announcements/issues/318

**Closed by blowdart** 2018-10-25 18:07 UTC
