### ISSUE TITLE
RC1 upgrade to RC2 - does SignInManager.IsSignedIn(User) replace User.Identity.IsAuthenticated?

### ISSUE THREAD

**Issue by pingcrosby** [aspnet/Identity#864] opened 2016-06-08 11:38 UTC
I have recently upgraded from RC1 to RC2 and am having some weird issues when i authenticate with an external provider.

Previously in RC1 my views were coded like this 

```
if(User.Identity.IsAuthenticated)
{
   <html .... />
}
```
This worked fine even if the user was from an external provider or internal login.  

However after upgrading to RC2 as soon as I use an external provider and I have not yet completed the `ExternalLoginCallback`, `ExternalLoginConfirmation ` sequence (from the boiler place AccountController) process, IsAuthenticated is always true and my views get rendered.  Internal logins work as expected only external provider logins cause issues.

To achieve the same functionality I have had to change to
```
@inject SignInManager<AppIdentityUser> SignInManager
@inject UserManager<AppIdentityUser> UserManager
 if (SignInManager.IsSignedIn(User)) // used to be User.Identity.IsAuthenticated in RC1
 {
    <html .... />
 }
```
Am i doing something fundementally wrong? Or is SignInManager.IsSignedIn the correct way?

Confused..

**Comment by HaoK** [comment] 2016-06-08 15:57
This is caused by https://github.com/aspnet/Identity/issues/848 and should be fixed in 1.0.0

**Closed by HaoK** 2016-06-08 15:57 UTC
