### ISSUE TITLE
Can't find a sample with roles authorization

### ISSUE THREAD

**Issue by vRITHNER** [aspnet/Identity#1241] opened 2017-05-24 05:19 UTC
From VS2017 preview, I created new Web App Mvc 2.0.0-preview1-final and Authentication Individual
![image](https://cloud.githubusercontent.com/assets/238842/26387728/13ad91a2-4050-11e7-971c-7a366d1906d2.png)

I need to manage Roles authorization in my own Controllers
I added Roles records ("Admin","User") and Users Roles etc. in the Sql Db.
When I try to add` [Authorize(Roles = "Admin")]` in one of my controller, I got "Access Denied";
With old `services.AddIdentity<ApplicationUser, ApplicationRole>() `in 1.1, it was working.

Any sample demoing this feature would be great
Txs

**Comment by blowdart** [comment] 2017-05-31 19:37
Dupe of https://github.com/aspnet/Identity/issues/1243

**Closed by blowdart** 2017-05-31 19:37 UTC
