### ISSUE TITLE
Navigation property for IdentityUserRole

### ISSUE THREAD

**Issue by jvelezc** [aspnet/Identity#753] opened 2016-02-22 21:10 UTC
public  class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, string>
{
 //giving me straight access instead of using RoleManager
    public DbSet<ApplicationRole> UserLogins { get; set; }
   public DbSet<ApplicationRole> Roles { get; set; }
   public DbSet<ApplicationUser> ApplicationUser { get; set; }
}
//If only https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityUserRole.cs

had a navigational property to roles I would have been able to get the role name!

var query = _dbCtx.AspNetUser
.Include(apu=>apu.AspNetUser.Roles).select(role=>role.Name)
.ToList();

Can I do a PR with navigational properties so that we can query directly using ApplicationContext instead of using the rolemanager? I can wait for RC2 to do it as well and if it doesnt have this feature add it.

**Comment by blowdart** [comment] 2016-02-24 22:06
Dupe of #610

**Closed by blowdart** 2016-02-24 22:06 UTC

**Comment by blowdart** [comment] 2016-02-24 22:09
@jvelezc Please feel free to create a PR against issue #610 and we'll take a look. There used to be some interesting problems with recursion that EF has now solved.

**Comment by jvelezc** [comment] 2016-02-26 00:18
Thank I will put a PR 610. I will work on this weekend.
