### ISSUE TITLE
Add FindByPhoneNumberAsync

### ISSUE THREAD

**Issue by Essen-Roc** [aspnet/Identity#1145] opened 2017-03-24 13:36 UTC
Used to phonenumber login.

In China, the mobile phone number is the only (by the system recycling to other people except the case), most of the App and Web sites are through the user name, mobile phone number login system, but use the email login situation very few hope to consider this problem!

Thank you.

**Comment by blowdart** [comment] 2017-03-29 19:30
Dupe of https://github.com/aspnet/Identity/issues/704

**Closed by blowdart** 2017-03-29 19:30 UTC
