### ISSUE TITLE
violate the type constraint when using

### ISSUE THREAD

**Issue by jvelezc** [aspnet/Identity#922] opened 2016-07-28 06:09 UTC
The database gets created but  I get the below exception here: 
```
     services.AddIdentity<ApplicationUser, ApplicationRole>()
                .AddEntityFrameworkStores<ApplicationDbContext, int>()
                .AddUserStore<CustomUserStore>()
                .AddDefaultTokenProviders();
```
I am trying to figure out the new RTM1.0 implementation with all the generics... I might be the first one outside of microsoft to try this. 

`   public class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, int,AspNetUserClaim,AspNetUserRole,AspNetUserLogin,AspNetRoleClaim,AspNetUserToken>`

![error](https://cloud.githubusercontent.com/assets/3653845/17202554/ceb27f56-544e-11e6-9149-646a354b4236.png)

Any test or examples of implementing

**Comment by ttaber** [comment] 2016-07-28 06:18
take a look at PR #893 
I ran into the same thing about a week ago.

**Comment by ttaber** [comment] 2016-07-28 06:25
try going with something like this:

UserStore:
`    public class ApplicationRoleStore : RoleStore<ApplicationRole, ApplicationDbContext, string, ApplicationUserRole, IdentityRoleClaim<string>>
    {
        public ApplicationRoleStore(ApplicationDbContext context, IdentityErrorDescriber describer = null) : base(context, describer)
        {
        }

        protected override IdentityRoleClaim<string> CreateRoleClaim(ApplicationRole role, Claim claim)
        {
            return new IdentityRoleClaim<string> { RoleId = role.Id, ClaimType = claim.Type, ClaimValue = claim.Value };
        }
    }`

UserStore:
 ` public class ApplicationUserStore : UserStore<ApplicationUser, ApplicationRole, ApplicationDbContext, string, ApplicationUserClaim, ApplicationUserRole, ApplicationUserLogin, ApplicationUserToken>
    {
        public ApplicationUserStore(ApplicationDbContext context) : base(context)
        {
        }

        protected override ApplicationUserClaim CreateUserClaim(ApplicationUser user, Claim claim)
        {
            return new ApplicationUserClaim { UserId = user.Id, ClaimType = claim.Type, ClaimValue = claim.Value };
        }

        protected override ApplicationUserLogin CreateUserLogin(ApplicationUser user, UserLoginInfo login)
        {
            return new ApplicationUserLogin
            {
                UserId = user.Id,
                ProviderKey = login.ProviderKey,
                LoginProvider = login.LoginProvider,
                ProviderDisplayName = login.ProviderDisplayName,
            };
        }

        protected override ApplicationUserRole CreateUserRole(ApplicationUser user, ApplicationRole role)
        {
            return new ApplicationUserRole()
            {
                RoleId = role.Id,
                UserId = user.Id,
            };
        }

        protected override ApplicationUserToken CreateUserToken(ApplicationUser user, string loginProvider, string name, string value)
        {
            return new ApplicationUserToken
            {
                UserId = user.Id,
                LoginProvider = loginProvider,
                Name = name,
                Value = value,
            };
        }
    }`

DBContext:
`    public class ApplicationDbContext : IdentityDbContext<ApplicationUser,ApplicationRole,string, ApplicationUserClaim, ApplicationUserRole,ApplicationUserLogin, IdentityRoleClaim<string>,ApplicationUserToken>`


Startup:
`            // Add framework services.
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")), ServiceLifetime.Transient);

            services.AddIdentity<ApplicationUser, ApplicationRole>()
                //.AddEntityFrameworkStores<ApplicationDbContext>() // No Longer Needed Due To Custom Identity Models
                .AddDefaultTokenProviders();

            services.AddScoped(typeof(IUserStore<ApplicationUser>), typeof(ApplicationUserStore))
                .AddScoped(typeof(IRoleStore<ApplicationRole>), typeof(ApplicationRoleStore));`

**Comment by ttaber** [comment] 2016-07-28 06:31
take a look at PR #893 
I ran into the same thing about a week ago.

**Comment by HaoK** [comment] 2016-08-08 20:26
Dupe of https://github.com/aspnet/Identity/issues/855

**Closed by HaoK** 2016-08-08 20:26 UTC
