### ISSUE TITLE
JWT Bearer Authentication : Set-Cookie in header response filled

### ISSUE THREAD

**Issue by N41m0r** [aspnet/Identity#1423] opened 2017-09-11 12:32 UTC
Hello,

I don't understand why i have a cookie filled in my response header while i use  JWT Bearer Authentication. And i can't find way how to configure correctly.

When I authenticate on my webAPI, in my reponse i have :  
`Set-Cookie: .AspNetCore.Identity.Application=CfDJ8KKk9DCF-3ZMv5e0QMpwpsulx6nT_6d68JTe0a8VPBM ...; path=/; samesite=lax; httponly
api-supported-versions: 1
`

My startup look like this : 

Configure : 

```
app.UseAuthentication();
app.UseMvc();
```

ConfigureServices : 

```
           services.Configure<IdentityOptions>(options =>
            {
                // Password settings
                options.Password.RequireDigit = true;
                options.Password.RequiredLength = 16;
                options.Password.RequireNonAlphanumeric = true;
                options.Password.RequireUppercase = true;
                options.Password.RequireLowercase = true;

                // User settings
                options.User.RequireUniqueEmail = true;
            });

            // Add framework services.
            services.AddEntityFrameworkNpgsql()
                .AddDbContext<ApplicationDbContext>(options => options.UseNpgsql(Configuration.GetConnectionString("ConnectionString")));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            services.AddAuthentication(options =>
                {
                    options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })
            .AddJwtBearer(options =>
                {
                    options.TokenValidationParameters = new AuthenticationConfiguration(Configuration).JwtTokenValidationParameters;
                    options.SaveToken = true;
                });

```

And for authenticate i use : 
```
var result = await _signInManager.PasswordSignInAsync(username, password, false, lockoutOnFailure: false);
```

Is there a way to have no cookie in my response header ?

Thx

**Comment by hey-red** [comment] 2017-09-11 17:25
See https://github.com/aspnet/Identity/issues/1376
With JWT you will have to manage the authentication yourself.

**Comment by HaoK** [comment] 2017-09-11 17:38
Yep, dupe of #1376

**Closed by HaoK** 2017-09-11 17:38 UTC

**Comment by jcmordan** [comment] 2017-09-12 00:41
@hey-red @HaoK  What do you mean by:

> With JWT you will have to manage the authentication yourself. 

I can't use _signInManager.PasswordSignInAsync anymore? what is the alternative?

**Comment by hey-red** [comment] 2017-09-12 05:57
@jcmordan 
You can achieve it like this:

```C#
var user = await _userManager.FindByNameAsync(userName);
if (user == null)
{
      return BadRequest("Invalid credentials");
 }

var result = await _signInManager.CheckPasswordSignInAsync(user, password, true);
if (!result.Succeeded)
{
      return BadRequest("Invalid credentials");
}

// Create token with user claims..
```

**Comment by N41m0r** [comment] 2017-09-12 07:49
@hey-red Thx, using CheckPasswordSignInAsync solved my problem.

**Comment by jcmordan** [comment] 2017-09-12 12:39
@hey-red when I do that a got this error:

```
InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.IUserLockoutStore`1[School360.Models.User]' while attempting to activate 'School360.Api.Controllers.AccountsController'.
Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)
```

Trying to solve it a Add the UserStorage<TUser> like this:

`builder.AddUserStore<UserStore<User>>();`

But then I got this error:

`InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContext' while attempting to activate 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`1[User]'.`

I had to add DbContext like this:

`services.TryAddScoped<DbContext, MyDbContext>();`

but I don't know if this is ok!
