### ISSUE TITLE
Allow customizing lifetime of 2FA codes for built in providers

### ISSUE THREAD

**Issue by suhasj** [aspnet/Identity#133] opened 2014-06-20 21:11 UTC
Changing the time for which the 2FA codes are valid is not possibly right now. Need to look into that

**Comment by suhasj** [comment] 2015-04-28 22:31
Removing milestone for it to be triaged. Need to review this request from a security perspective.

**Comment by HaoK** [comment] 2015-05-05 00:04
Probably can just add a Timespan expiries to the options per provider, one knob per TokenProvider class seems reasonable, @blowdart  thoughts?

**Comment by blowdart** [comment] 2015-05-05 19:50
Timespan works for me

**Comment by HaoK** [comment] 2015-06-08 18:14
Dupe of https://github.com/aspnet/Identity/issues/465

**Closed by HaoK** 2015-06-08 18:14 UTC
