### ISSUE TITLE
Q: moving of source

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Identity#2085] opened 2018-11-29 21:48 UTC
Is the identity repo under the aspnet/aspnetcore like other repos have ?

**Comment by blowdart** [comment] 2018-11-30 14:07
It will be, eventually. @natemcmaster

**Comment by natemcmaster** [comment] 2018-12-01 01:11
Yes, started the work today. It probably won't merge till Monday. Part 1: https://github.com/aspnet/AspNetCore/pull/4345. There will be a second piece to move the Microsoft.Extensions.* projects into https://github.com/aspnet/Extensions.

Closing as a duplicate of https://github.com/aspnet/AspNetCore/issues/3598

**Closed by natemcmaster** 2018-12-01 01:11 UTC

**Comment by grahamehorner** [comment] 2018-12-01 13:30
@natemcmaster not sure if your aware but I'm seeing a few build errors with repo's that have moved; (Blazor) due to path length, I understand these are WIP where would be the best to raise the build issues?

**Comment by natemcmaster** [comment] 2018-12-03 17:04
Raise the issue on the new repo.
