### ISSUE TITLE
InMemoryEFUserStoreTest tests failing with BadImageFormatException on Win7

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Identity#1149] opened 2017-03-28 16:28 UTC
It appears almost all tests (194) in InMemoryEFUserStoreTest are failing in Win 2008 and Win 7 with this error:
```
System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Interop.mincore.NormalizeString(Int32 normForm, String source, Int32 sourceLength, Char[] destination, Int32 destinationLength)
   at System.StringNormalizationExtensions.Normalize(String strInput, NormalizationForm normalizationForm)
   at Microsoft.AspNetCore.Identity.UpperInvariantLookupNormalizer.Normalize(String key)
   at Microsoft.AspNetCore.Identity.UserManager`1.NormalizeKey(String key)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateUserName>d__6.MoveNext()
```

See http://aspnetci/viewLog.html?buildId=193577&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win2008r2_Universe

**Comment by ajcvickers** [comment] 2017-03-29 01:56
@HaoK Can you please investigate why these tests are failing?

**Comment by HaoK** [comment] 2017-03-29 07:10
This looks to be the same exception as https://github.com/aspnet/Identity/issues/882

**Comment by HaoK** [comment] 2017-03-29 07:14
@natemcmaster did these tests just start failing recently on Win 2008/Win7 or have they always failed?

This looks like a potentially related bug that's open currently https://github.com/dotnet/coreclr/issues/6392

**Comment by natemcmaster** [comment] 2017-03-29 16:17
They started failing March 22.

**Comment by HaoK** [comment] 2017-03-29 18:24
Strange, do you know if there was any integrations around that time from coreclr?  In the past similar issues seemed to be a bug in windows

**Comment by HaoK** [comment] 2017-03-29 18:25
Identity is basically the only place in our code today that uses string.NormalizeString which is why its the canary that keeps dying :)

**Comment by natemcmaster** [comment] 2017-03-29 19:49
Actually, these failures are not .NET Core. It appears these failures were caused by switching from .NET Framework 4.5.2 to .NET Framework 4.6. cref https://github.com/aspnet/Identity/commit/234b8827583fc6c1d9888a426b38d9057a72418a

**Comment by natemcmaster** [comment] 2017-03-29 19:53
Once you trim ~45,000 lines from the build log, you'll see this:
```
(.NET Core 1.1)
Test run for C:\BuildAgent\work\2b0c8ce712895332\.r\Identity\test\Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test\bin\Release\netcoreapp1.1\Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.dll(.NETCoreApp,Version=v1.1)
Total tests: 208. Passed: 208. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 8.6992 Seconds

(.NET Framework 4.6)
Test run for C:\BuildAgent\work\2b0c8ce712895332\.r\Identity\test\Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test\bin\Release\net46\Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.dll(.NETFramework,Version=v4.6) 
Starting test execution, please wait...
Failed   Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.InMemoryEFUserStoreTest.CanFindRoleWithManager
Error Message:
 System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
Stack Trace:
   at Interop.mincore.NormalizeString(Int32 normForm, String source, Int32 sourceLength, Char[] destination, Int32 destinationLength)
   at System.StringNormalizationExtensions.Normalize(String strInput, NormalizationForm normalizationForm)
   at Microsoft.AspNetCore.Identity.UpperInvariantLookupNormalizer.Normalize(String key)
   at Microsoft.AspNetCore.Identity.RoleManager`1.NormalizeKey(String key)
   at Microsoft.AspNetCore.Identity.RoleManager`1.FindByNameAsync(String roleName)
   at Microsoft.AspNetCore.Identity.RoleValidator`1.<ValidateRoleName>d__6.MoveNext()
Total tests: 208. Passed: 12. Failed: 196. Skipped: 0.
Test Run Failed.
Test execution time: 10.1455 Seconds
```

**Comment by HaoK** [comment] 2017-03-29 19:54
So this is basically String.Normalize doesn't work on net46 on Win2008/Win7

**Comment by HaoK** [comment] 2017-03-29 19:55
I wonder what crazy stuff they are doing to normalize strings, because it appears to be quite delicate :)

**Comment by divega** [comment] 2017-03-29 20:10
FWIW, the code changed quite a bit in https://github.com/dotnet/coreclr/pull/9941.

**Comment by HaoK** [comment] 2017-03-29 20:11
Honestly, it almost doesn't seem worth it to be calling this API given how fragile it is...

**Comment by ajcvickers** [comment] 2017-03-29 20:20
@HaoK Can you follow up with the people on https://github.com/dotnet/coreclr/issues/6392 and confirm that the failure that we are seeing is being tracked by this issue? @tarekgh might be another good person to follow up with. If this is the correct issue, can you try to find out when we expect it to be fixed?

@Eilon We probably need to track this as blocking us, at least on these platforms. Do we just mark their issue as blocking, or are there also additional positive hand-off steps we should do?

**Comment by tarekgh** [comment] 2017-03-29 20:35
Could you clarify what really the issue I can help with? dotnet/coreclr#6392 is really old issue and I think shouldn't repro with the latest netcore versions. Also people assigned this issue can help with the old version.

**Comment by HaoK** [comment] 2017-03-29 20:48
Basically it appears these failures were caused by switching from .NET Framework 4.5.2 to .NET Framework 4.6, the only tests that are failing from this change are the tests that are calling into string.Normalize, so we think something in there has caused this regression

   at Interop.mincore.NormalizeString(Int32 normForm, String source, Int32 sourceLength, Char[] destination, Int32 destinationLength)
   at System.StringNormalizationExtensions.Normalize(String strInput, NormalizationForm normalizationForm)
   at Microsoft.AspNetCore.Identity.UpperInvariantLookupNormalizer.Normalize(String key)

**Comment by tarekgh** [comment] 2017-03-29 20:52
yes that is what the issue dotnet/coreclr#6392 is saying. basically looks the APISET DLL was missing from the deployment and people on the issue can help with that. I don't expect this issue repro in the latest versions of netcore because we have changed of using the APISET DLLs and instead we are calling teh actual library.

**Comment by HaoK** [comment] 2017-03-29 20:55
@piotrpMSFT can you confirm that the test failures we are seeing on net46 with string.Normalize  are being tracked by https://github.com/dotnet/coreclr/issues/6392?

**Comment by tarekgh** [comment] 2017-03-29 21:00
There is one thing that is unclear here. the call System.StringNormalizationExtensions.Normalize shouldn't occur on net46 at all and instead String.Normalize should be called. if the test is intentionally calling StringNormalizationExtensions then the test is wrong and need to be fixed to run on the desktop.

**Comment by HaoK** [comment] 2017-03-29 21:04
We are just calling `string.Normalize().ToUpperInvariant();` is that not supported anymore?

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/UpperInvariantLookupNormalizer.cs#L25

**Comment by tarekgh** [comment] 2017-03-29 21:07
In this case you are not really running against desktop net46 and I guess you are running against netcore. I am saying that because if you are calling String.Normalize then StringNormalizationExtensions.Normalize shouldn't get called at all. could you confirm if the test running against the full framework or running against net core?

**Comment by HaoK** [comment] 2017-03-29 21:14
From the build log snippet above, it appears to be net46:

```
(.NET Core 1.1)
Test run for C:\BuildAgent\work\2b0c8ce712895332\.r\Identity\test\Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test\bin\Release\netcoreapp1.1\Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.dll(.NETCoreApp,Version=v1.1)
Total tests: 208. Passed: 208. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 8.6992 Seconds

(.NET Framework 4.6)
Test run for C:\BuildAgent\work\2b0c8ce712895332\.r\Identity\test\Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test\bin\Release\net46\Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.dll(.NETFramework,Version=v4.6) 
Starting test execution, please wait...
Failed   Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.InMemoryEFUserStoreTest.CanFindRoleWithManager
Error Message:
 System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
Stack Trace:
   at Interop.mincore.NormalizeString(Int32 normForm, String source, Int32 sourceLength, Char[] destination, Int32 destinationLength)
   at System.StringNormalizationExtensions.Normalize(String strInput, NormalizationForm normalizationForm)
   at Microsoft.AspNetCore.Identity.UpperInvariantLookupNormalizer.Normalize(String key)
```

**Comment by Eilon** [comment] 2017-03-29 21:21
@HaoK can you create a standalone repro project and upload to GitHub? Seems like it should be easy to repro?

**Comment by tarekgh** [comment] 2017-03-29 21:25
ok now I think I understand what is going on. 
Looks what is happening is you built the bits that need to run against net46 using the netcore assemblies and that is why StringNormalizationExtensions.Normalize get called and not String.Normalize. in same time the extension method is pinvoking to APISET DLL which doesn't exist on Win7 and need to deploy it. 

To fix this is either you link to the APISET package to get it in your deployment

https://www.nuget.org/packages/Microsoft.NETCore.Windows.ApiSets/ 

or you need to build your code against the full framework and not net core

**Comment by pranavkm** [comment] 2017-03-29 21:55
@tarekgh the package targets `netstandard1.3` which should support `net46` according to the specs - https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.3.md. Plus, the tests run fine on OSes later than Win7. It doesn't seem like an issue with this package.

**Comment by HaoK** [comment] 2017-03-29 22:00
The repro for https://github.com/dotnet/corefx/issues/9650 should still apply:

`Console.WriteLine("Hello World!".Normalize());`

**Comment by tarekgh** [comment] 2017-03-29 22:01
> Plus, the tests run fine on OSes later than Win7. It doesn't seem like an issue with this package.

that is because Windows versions post Windows 7 has the APISETS installed on the system. the bottom line here is you need to have the APISET on your system to be able to run. as I mentioned before either you need to get it from the package or you need to compile against full framework.

**Comment by ericstj** [comment] 2017-03-29 22:16
@tarekgh / @gkhanna79 I thought we changed the coreclr/corefx platform dependencies back to the classic identities rather than API sets.

**Comment by tarekgh** [comment] 2017-03-29 22:16
>  I thought we changed the coreclr/corefx platform dependencies back to the classic identities rather than API sets.

yes we did but it looks they still referencing the old version

**Comment by ericstj** [comment] 2017-03-29 22:18
@tarekgh can you make sure we're building a new asset in this package with the fix for desktop?  If so, then the answer is "use the newer package".

**Comment by pranavkm** [comment] 2017-03-29 22:24
Is the newer package `NS.Library 2.0.0`?

**Comment by tarekgh** [comment] 2017-03-30 01:41
> @tarekgh can you make sure we're building a new asset in this package with the fix for desktop? If so, then the answer is "use the newer package".

The version of this library package on NuGet is the one which has the old implementation which is depending on the APISET
 
https://www.nuget.org/packages/runtime.win7.System.Globalization.Extensions/4.0.1-beta-23516

The one we are currently building for netstandard 2.0.0 we just type forward to System.Runtime and in  System.Runtime we have the extension methods implementation just calling the String Normalize/IsNormalized. so there is no APISET set in this version. 

@ericstj looks they are targeting netstandard 1.3. what is the best they can do here? should they use the package https://www.nuget.org/packages/Microsoft.NETCore.Windows.ApiSets/ to get the missing APISETs? or you have other ideas?

**Comment by pranavkm** [comment] 2017-03-30 03:02
We'll be switching to NETStandard.Library 2.0.0-* soon, while still targeting `netstandard1.3`. If the problem goes away in that case, maybe we can disable these tests for the time being and re-enable it once the migration is done.

**Comment by HaoK** [comment] 2017-03-30 16:57
I'll just remove the call to Normalize for now until we are on NetStandard 2.0 to unblock the tests.

**Comment by ajcvickers** [comment] 2017-03-30 18:53
Let's be sure this doesn't fall under the table. If we think this is a point-in-time thing, then making the change to unblock our builds is okay. But we need to make sure that we are ultimately:
* Building things in a way that they should work (we're not doing it wrong)
* The shipped netfx packages are correct and doing the right thing (partner teams are not doing it wrong)

Us consuming these bits is a way to verify partner team bits, and as such, we must make sure we don't _only_ work around issues, but also make sure that the underlying problem is fixed so that our customers won't start hitting it.

Leaving this assigned to @HaoK to track. @pranavkm Can we get a ping when we should try this again?

**Comment by pranavkm** [comment] 2017-03-30 18:57
Yup. I filed https://github.com/aspnet/Identity/issues/1153 to track it in this repo and marked this as a follow up issue in our repo migration tracker - https://github.com/aspnet/Coherence/issues/166

**Comment by HaoK** [comment] 2017-08-07 18:55
Looks like everything was undone now as all the linked issues are closed merged

**Closed by HaoK** 2017-08-07 18:55 UTC
Labels: Blocked!, needs-investigation
